### ISSUE TITLE
calico not getting installed

### ISSUE THREAD

**Issue by livespotty** [oracle-terraform-modules/terraform-oci-oke#109]
I get the following error after enabling calico

calico_version = "3.9"

install_calico = true

==========Error=============
module.oke.null_resource.install_calico[0] (remote-exec): unable to recognize "calico-policy-only.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused
==========Error=============

I do not see calico; Here is the get pods output.

NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE
kube-system   kube-dns-autoscaler-7c97bb6dfb-w9tpd    1/1     Running   0          24m
kube-system   kube-dns-bdb5cb4bd-9rfdk                3/3     Running   0          17m
kube-system   kube-dns-bdb5cb4bd-gjg75                3/3     Running   0          17m
kube-system   kube-dns-bdb5cb4bd-t9nml                3/3     Running   0          24m
kube-system   kube-flannel-ds-2hzcr                   1/1     Running   1          17m
kube-system   kube-flannel-ds-bscwq                   1/1     Running   1          17m
kube-system   kube-flannel-ds-tntk4                   1/1     Running   1          17m
kube-system   kube-proxy-58s86                        1/1     Running   0          17m
kube-system   kube-proxy-cx86z                        1/1     Running   0          17m
kube-system   kube-proxy-dblh4                        1/1     Running   0          17m
kube-system   kubernetes-dashboard-768d48d6c9-xfjjr   1/1     Running   0          24m
kube-system   proxymux-client-10.0.64.2               1/1     Running   0          17m
kube-system   proxymux-client-10.0.64.3               1/1     Running   0          17m
kube-system   proxymux-client-10.0.64.4               1/1     Running   0          17m

**Comment by livespotty** [comment]
Found out the root cause of this issue.
Admin node did not have copy of kubeconfig in $HOME/.kube that was causing this problem.

**Comment by hyder** [comment]
That's odd, let me check the dependencies. It is possible that because of the switch to run this on the admin node, the explicit dependencies got messed up.

**Comment by livespotty** [comment]
This problem was caused by #110, hence closing this issue.
