### ISSUE TITLE
admin does not have kube config causing other issues

### ISSUE THREAD

**Issue by livespotty** [oracle-terraform-modules/terraform-oci-oke#110]
Admin node does not have kube config file and causing several other issues pertaining to install additional tools such as calico and metrics server.

see issue #109  

[opc@admin .kube]$ ls -ltra
total 4
drwxrwxr-x. 2 opc opc    6 Dec 13 08:50 .
drwx------. 8 opc opc 4096 Dec 13 08:51 ..
[opc@admin .kube]$

**Comment by hyder** [comment]
You need to enable instance_principal for the admin_server in order for the it to be able to get the kubeconfig file:

admin_instance_principal = true

Can you please try this and let us know?

**Comment by livespotty** [comment]
Awesome, it works now thanks!

**Comment by hyder** [comment]
Cool. I think the documentation didn't explicitly call these dependencies out. We'll fix this
