### ISSUE TITLE
Issue with applying keyvault for Encrypting Kubernetes Secrets

### ISSUE THREAD

**Issue by livespotty** [oracle-terraform-modules/terraform-oci-oke#112]
Followed the https://docs.cloud.oracle.com/iaas/Content/ContEng/Tasks/contengencryptingdata.htm

Created dynamic group and policies as per above link

Below attributes are set as per documentation.

**use_encryption = true

existing_key_id = "ocid1.keyxxxxxxxxxxxxxxxxxxxxxxxx"**

==================
**Error: Unsupported attribute**

 on modules/policies/locals.tf line 10, in locals:
  10:   policy_statement = (var.oke_kms.use_encryption == true) ? "Allow dynamic-group ${oci_identity_dynamic_group.oke-kms-cluster[0].name} to use keys in compartment ${var.oci_identity.compartment_name} where target.key.id = '${var.oke_kms.key_id}'" : ""
    |----------------
    | var.oci_identity is object with 5 attributes

This object does not have an attribute named "compartment_name".

**Comment by hyder** [comment]
Hi,

Yes, this looks like a bug. Sorry about that - it's a remnant of refactoring.

Can you try replacing the policy statement with this:

policy_statement = (var.oke_kms.use_encryption == true) ? "Allow dynamic-group ${oci_identity_dynamic_group.oke-kms-cluster[0].name} to use keys in compartment id ${data.oci_identity_compartments.compartments_id.compartments.0.id}" where target.key.id = '${var.oke_kms.key_id}'" : ""

and let us know how you go?

**Comment by livespotty** [comment]
I removed the additional **quote** and the following revised policy statement worked.

policy_statement = (var.oke_kms.use_encryption == true) ? "Allow dynamic-group ${oci_identity_dynamic_group.oke-kms-cluster[0].name} to use keys in compartment id ${data.oci_identity_compartments.compartments_id.compartments.0.id} where target.key.id = '${var.oke_kms.key_id}'" : ""

**Comment by hyder** [comment]
Thanks for testing. Will include it in the next release.

**Comment by hyder** [comment]
@livespotty fixed in #115
