### ISSUE TITLE
oci_ons_notification_topic.bastion_notification is empty tuple

### ISSUE THREAD

**Issue by scanlonjts** [oracle-terraform-modules/terraform-oci-oke#121]
fresh install
setting bastion_enabled = false

Error: Invalid index

  on .terraform\modules\base\modules\bastion\datasources.tf line 69, in data "oci_ons_notification_topic" "bastion_notification":
  69:   topic_id = oci_ons_notification_topic.bastion_notification[0].topic_id
    |----------------
    | oci_ons_notification_topic.bastion_notification is empty tuple

The given key does not identify an element in this collection value.

should not continue the bastion notification setup if no bastion 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by scanlonjts** [comment]
Thanks for the reply. By disabling the notification I was able to setup already. Fixing the logic will prevent others from having to do the same

**Comment by hyder** [comment]
Hi, it's now fixed in the base module. Can you please test and confirm?

**Comment by hyder** [comment]
@scanlonjts can you please check?

**Comment by hyder** [comment]
Closing due to lack of response
