### ISSUE TITLE
Issue with bastion creation

### ISSUE THREAD

**Issue by livespotty** [oracle-terraform-modules/terraform-oci-oke#123]
------------------------------------------------------------------------

Error: Invalid index

  on .terraform/modules/base/modules/bastion/datasources.tf line 40, in data "template_cloudinit_config" "bastion":
  40:     content      = data.template_file.autonomous_cloud_init_file[0].rendered
    |----------------
    | data.template_file.autonomous_cloud_init_file is empty tuple

**Comment by hyder** [comment]
You need to enable the admin host:

admin_enabled = true

**Comment by livespotty** [comment]
> You need to enable the admin host:
> 
> admin_enabled = true

admin host is enabled and its the same issue

**Comment by livespotty** [comment]
Found out the issue, bastion image id was set to "NONE"
bastion_image_id = "NONE"

correct value should be set to "Autonomous"

**Comment by hyder** [comment]
Ok thanks. Make sure you don't use Autonomous for admin for the time being.
