### ISSUE TITLE
Issue while installing calico - remote-exec error

### ISSUE THREAD

**Issue by livespotty** [oracle-terraform-modules/terraform-oci-oke#126]
module.oke.null_resource.install_calico[0] (remote-exec): unable to recognize "calico-policy-only.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused
module.oke.null_resource.install_calico[0]: Creation complete after 14s [id=310330431674851063]

Error: error executing "/tmp/terraform_812903520.sh": Process exited with status 1

Error: error executing "/tmp/terraform_1105940682.sh": Process exited with status 1

================================================

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by livespotty** [comment]
found out the root cause of this issue. **oci** cli tool is not getting installed on admin host

==================
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Checking Host Key: false
module.policies.null_resource.update_dynamic_group[0] (remote-exec): Connected!
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec): Connected!
module.policies.null_resource.update_dynamic_group[0] (remote-exec): /home/opc/update_dynamic_group.sh: line 5: oci: command not found

**Comment by livespotty** [comment]
The fix is to modify the following script 
/modules/oke/scripts/install_kubectl.template.sh

and add the following line
sudo yum install -y python-oci-cli-2.9.0-1.el7

this will install oci-cli tool.

**Comment by hyder** [comment]
Ok thanks. I will fix this in the base module accordingly

**Comment by hyder** [comment]
Hi, I was not able to replicate the issue. oci-cli installed correctly as the generation of kubeconfig and the subsequent installation of calico. Can you please share your var file (minus the credentials)?

**Comment by livespotty** [comment]
This issue was because of the new OL image for Admin server. The oracle-oclne-release-el7 package was broken. I tested with old OL image and it was fine.

**Comment by hyder** [comment]
The oracle-oclne-release-el7 is used only for kubectl, not for oci-cli which is what you reported the issue. Does the problem still exist or we can close this?

**Comment by livespotty** [comment]
Closed this issue, since this problem was due to OL image.
