### ISSUE TITLE
Remove provider.tf to make this project a reusable module from the registry

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-oke#130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by sauraahu** [comment]
Review https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/137 for the fix.

**Comment by hyder** [comment]
Hi, 

Thanks for your contribution. Please also update the docs for the following scenarios in the quickstart page:

1. Users are cloning this repo instead of using the published module. This means they'll need to add the provider.tf themselves. The provider will need to be as it is currently defined.
2. Users are using the published module from the registry. Please document how they should then use the module, including defining the provider and passing the various parameters etc.

**Comment by hyder** [comment]
Done in #139
