### ISSUE TITLE
/home/opc/generate_kubeconfig.sh: line 5: oci: command not found

### ISSUE THREAD

**Issue by ldessemon2** [oracle-terraform-modules/terraform-oci-oke#136]
...
module.oke.local_file.kube_config_file: Creation complete after 0s [id=0073ab2f827a123dada44eff4abfda89e673ebd5]
module.oke.null_resource.write_kubeconfig_on_admin[0]: Provisioning with 'remote-exec'...
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec): Connecting to remote host via SSH...
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Host: 10.0.1.10
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   User: opc
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Password: false
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Private key: true
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Certificate: false
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   SSH Agent: true
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Checking Host Key: false
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec): Using configured bastion host...
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Host: 132.145.98.142
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   User: opc
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Password: false
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Private key: true
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Certificate: false
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   SSH Agent: true
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec):   Checking Host Key: false
module.oke.oci_containerengine_node_pool.nodepools[0]: Creation complete after 1s [id=ocid1.nodepool.oc1.ca-toronto-1.aaaaaaaaafrdcmrvgjrwcn3bgmydmzrrg42daobtheztoyrugnrgeztggjrw]
module.oke.data.oci_containerengine_node_pools.all_node_pools: Refreshing state...
module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec): Connected!
**module.oke.null_resource.write_kubeconfig_on_admin[0] (remote-exec): /home/opc/generate_kubeconfig.sh: line 5: oci: command not found**
module.oke.null_resource.write_kubeconfig_on_admin[0]: Creation complete after 2s [id=3895753161101986324]
module.oke.null_resource.create_service_account[0]: Creating...
module.oke.null_resource.create_service_account[0]: Provisioning with 'file'...
module.oke.null_resource.create_service_account[0]: Provisioning with 'remote-exec'...
module.oke.null_resource.create_service_account[0] (remote-exec): Connecting to remote host via SSH...
module.oke.null_resource.create_service_account[0] (remote-exec):   Host: 10.0.1.10
module.oke.null_resource.create_service_account[0] (remote-exec):   User: opc
module.oke.null_resource.create_service_account[0] (remote-exec):   Password: false
module.oke.null_resource.create_service_account[0] (remote-exec):   Private key: true
module.oke.null_resource.create_service_account[0] (remote-exec):   Certificate: false
module.oke.null_resource.create_service_account[0] (remote-exec):   SSH Agent: true
module.oke.null_resource.create_service_account[0] (remote-exec):   Checking Host Key: false
module.oke.null_resource.create_service_account[0] (remote-exec): Using configured bastion host...
module.oke.null_resource.create_service_account[0] (remote-exec):   Host: 132.145.98.142
module.oke.null_resource.create_service_account[0] (remote-exec):   User: opc
module.oke.null_resource.create_service_account[0] (remote-exec):   Password: false
module.oke.null_resource.create_service_account[0] (remote-exec):   Private key: true
module.oke.null_resource.create_service_account[0] (remote-exec):   Certificate: false
module.oke.null_resource.create_service_account[0] (remote-exec):   SSH Agent: true
module.oke.null_resource.create_service_account[0] (remote-exec):   Checking Host Key: false
module.oke.null_resource.create_service_account[0] (remote-exec): Connected!
module.oke.null_resource.create_service_account[0] (remote-exec): The connection to the server localhost:8080 was refused - did you specify the right host or port?
module.oke.null_resource.create_service_account[0] (remote-exec): The connection to the server localhost:8080 was refused - did you specify the right host or port?

Error: error executing "/tmp/terraform_1823839862.sh": Process exited with status 1

ludovicdessemon@ludovicdessemon-mac terraform-oci-oke %

**Comment by hyder** [comment]
Hi, which image are you using for the Admin host?

**Comment by hyder** [comment]
Hi, I'm closing this due to lack of response. If you're still encountering it, please reopen this issue.
