### ISSUE TITLE
Unable to do terraform plan or it is not supporting latest terraform version or something missing in instructions

### ISSUE THREAD

**Issue by sauraahu** [oracle-terraform-modules/terraform-oci-oke#138]
This is my terraform version:
Terraform v0.12.23
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.oci v3.67.0
+ provider.template v2.1.2

1. copied terraform.tfvars.example to terraform.tfvars. Filled all mandatory details in terraform.tfvars
2. terraform init
3. terraform plan, which results in below error message- 
module.policies.data.oci_identity_regions.home_region: Refreshing state...
module.base.data.oci_identity_regions.home_region: Refreshing state...
------------------------------------------------------------------------
Error: Invalid index
  on .terraform/modules/base/oracle-terraform-modules-terraform-oci-base-963da7b/modules/admin/instance_principal.tf line 42, in resource "oci_identity_policy" "admin_instance_principal":
  42:   statements     = ["Allow dynamic-group ${oci_identity_dynamic_group.admin_instance_principal[0].name} to manage all-resources in compartment id ${data.oci_identity_compartments.compartments_id.compartments.0.id}"]
    |----------------
    | data.oci_identity_compartments.compartments_id.compartments is empty list of object
The given key does not identify an element in this collection value.
Error: Invalid index
  on .terraform/modules/base/oracle-terraform-modules-terraform-oci-base-963da7b/modules/bastion/ons.tf line 61, in resource "oci_identity_policy" "bastion_notification":
  61:   statements     = ["Allow dynamic-group ${oci_identity_dynamic_group.bastion_notification[0].name} to use ons-topic in compartment id ${data.oci_identity_compartments.compartments_id[0].compartments.0.id} where request.permission='ONS_TOPIC_PUBLISH'"]
    |----------------
    | data.oci_identity_compartments.compartments_id[0].compartments is empty list of object

The given key does not identify an element in this collection value.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by hyder** [comment]
hi, the user probably does not have the necessary permissions. We have an issue open to document the required IAM requirements: https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/108

**Comment by hyder** [comment]
Hi,

Are you still encountering this problem?

**Comment by sauraahu** [comment]
Well, i still need to work on IAM requirements, i will update you. You are right, i may be missing necessary permissions

**Comment by sauraahu** [comment]
Yeah, stuck as dynamic group and policies: If document is created for expected dynamic group. Things should pass

Error: Invalid index

  on .terraform/modules/terraform-oci-oke.base/terraform-oci-base-1.1.1/modules/admin/instance_principal.tf line 42, in resource "oci_identity_policy" "admin_instance_principal":
  42:   statements     = ["Allow dynamic-group ${oci_identity_dynamic_group.admin_instance_principal[0].name} to manage all-resources in compartment id ${data.oci_identity_compartments.compartments_id.compartments.0.id}"]
    |----------------
    | data.oci_identity_compartments.compartments_id.compartments is empty list of object

**Comment by sauraahu** [comment]
I root caused this issue related to root compartment, when i use child compartment it works fine. You can close this issue. I have opened separate issue for using root compartment or document as folks wont be aware of it.
