### ISSUE TITLE
OCI CLI Config

### ISSUE THREAD

**Issue by emanuelgrama** [oracle-terraform-modules/terraform-oci-oke#140]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** OKE module.

If you have a support request or question related to core Terraform functionality or the OCI provider, please submit them to one of these resources:

* [Terraform OCI provider](https://github.com/terraform-providers/terraform-provider-oci)
* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by emanuelgrama** [comment]
Hello,

I have one question regarding oci cli config: how is this handled here? If you don't have a configured oci cli and PEM key added in oci console will fail at "generate_kubeconfig".Using instance principal still errors out at :  "oci ce cluster create-kubeconfig --cluster-id ${cluster-id} --file $HOME/.kube/config  --region ${region} --token-version 2.0.0"

Thanks

**Comment by hyder** [comment]
Hi, 

Adding the PEM key in OCI console is necessary for the user terraform will be using. This is required so the terraform oci provider can be configured. 

As for generating the kubeconfig, this is done on the admin host. So, this needs to be enabled as well as the instance_principal:

```
admin_enabled = true
admin_instance_principal = true
```

If you are having trouble with the necessary options, the [terraform.tfvars.example](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/terraform.tfvars.example) file provides some sensible defaults.

**Comment by hyder** [comment]
Can you please try https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/146 and see if this solves the problem? I think the issues are related.

**Comment by emanuelgrama** [comment]
I managed to resolved it with instance principal.

Thanks

**Comment by hyder** [comment]
Ok thanks. Can we close your issue then?

**Comment by emanuelgrama** [comment]
Yes, we can close it.

Thanks
