### ISSUE TITLE
Add vcn_id to output variables

### ISSUE THREAD

**Issue by styledigger** [oracle-terraform-modules/terraform-oci-oke#145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When you consume this module in your terraform script by referencing it like this:
```
module "oke" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "2.1.4"
  # insert the 23 required variables here
}
```
you do not have access vcn_id created by `oracle-terraform-modules/base/oci` module. This makes it hard to add new respources to the same VCN.
Adding vcn_id to output variables will help anybody who needs to augment OKE deployment with additional resources provisioned in the same VCN (e.g. autonomous database).

### New or Affected Resource(s)
the feature can be implemented by adding following code to outputs.tf:
```
output "vcn_id" {
  description = "VCN OCID"
  value       = module.base.vcn_id
}

```
### Potential Terraform Configuration
Parrent module can then access vcn_id value like this:

```hcl
vcn_id = module.oke.vcn_id 
```

**Comment by hyder** [comment]
Fixed in #147. Added a few more network parameters in case you need them
