### ISSUE TITLE
Add serviceaccount to kubeconfig

### ISSUE THREAD

**Issue by styledigger** [oracle-terraform-modules/terraform-oci-oke#152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Once we create service account, lets add it as a user definition to the kubeconfig file so that kubectl can use service account to authenticate to OKE. Benefits:
- one can access OKE even without having associated OCI user account
- this can be used by automation tools/scripts such as CI/CD

### New or Affected Resource(s)
Attached is a script template `modules\oke\scripts\generate_kubeconfig_sa.template.sh` and a tf file `modules\oke\kubeconfig_sa.tf` that renders and calls the script.

[tf_kubeconfig_sa.zip](https://github.com/oracle-terraform-modules/terraform-oci-oke/files/4468394/tf_kubeconfig_sa.zip)

Script creates a copy of original kubeconfig file named config-sa, adds service account to that file and sets it as a default user. 
It would be great to also have that file copied to local machine. I do not know of any way terraform can do that. I tried using scp command via loca_exec (see the commented part at the bottom of kubeconfig_sa.tf), however scp is interactive command, it asks for accepting remote host ssh keys. So I resorted to at least rendering and displaying scp command to end user so that she/he can run it on her/his own once terraform apply finishes. That requires 2 additional changes:
1) add following code to modules\oke\outputs.tf
```
output "scp_command" {
  value = "scp -i ${var.oke_ssh_keys.ssh_private_key_path} -o ProxyCommand=\"ssh -i ${var.oke_ssh_keys.ssh_private_key_path} -W %h:%p opc@${var.oke_admin.bastion_public_ip}\" opc@${var.oke_admin.admin_private_ip}:~/.kube/config-sa ${path.root}/generated/kubeconfig-sa"
```

2) add following code to .\outputs.tf
```
output "get_kubeconfig_sa" {
  description = "get kubeconfig-sa from admin host"
  value       = module.oke.scp_command
}

``` 

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

### References

https://docs.cloud.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengaddingserviceaccttoken.htm

**Comment by hyder** [comment]
I've discussed this with our engineering team and their opinion is that using service accounts to replace user authentication isn't a good practice as we would lose all attribution. Using it for ci/cd and stuff is more acceptable. So unfortunately, we won't be accepting this.
