### ISSUE TITLE
Add option to use existing VCN

### ISSUE THREAD

**Issue by stefankoser** [oracle-terraform-modules/terraform-oci-oke#163]
Terraform scripts for OKE should allow to use an existing VCN to provision OKE. This is to preserve existing local/remote peering configuration, for example. Also if we need to have a cluster in same VCN as other services (ADB).

!--- Please keep this note for the community --->

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by torstenboe** [comment]
Same here, urgently needed: reusing the oci_base_vcn similar to oci_base_bastion and oci_base_operator.

**Comment by hyder** [comment]
After a lot of discussion, we've determined that reusing an existing VCN 1) would be very hard to implement 2) has the potential to create a lot more errors elsewhere, either during cluster creation or subsequent deletion. We have reluctantly concluded that we will not fix implement this feature for now.

We may revisit this when Terraform 0.13 is out when conditional modules will be added.

**Comment by hyder** [comment]
@karthicgit reopening this issue. let's discuss.

**Comment by hyder** [comment]
Added in #175
