### ISSUE TITLE
would be possible to implement a "waiting state" until all the worker nodes are ready ?

### ISSUE THREAD

**Issue by eugsim1** [oracle-terraform-modules/terraform-oci-oke#164]
Hi I m using your excellent implementation, but i m hitting a feature of the terraform kubernetes call.
Whenever i want to modify the pool size expand/reduce the request is executed immediately ie the terraform scripts are setting up the new pool size, but the creation of the nodes is taking time and the new configuration is not ready yet meanwhile the terraform script has finished the excution.
If i have another scirpt which has to run on the new pool it will fail as the nodes are not ready yet.
would be possible to implement a flag like "keep_pooling_until_all_nodes_are_ready" so the execution of the terraform script will finish when the pool is having the new settings ?
thanks
eugene

**Comment by hyder** [comment]
done in #174
