### ISSUE TITLE
Update base module and move from oci_base_admin to oci_base_operator

### ISSUE THREAD

**Issue by torstenboe** [oracle-terraform-modules/terraform-oci-oke#165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Since the base module was split in to three separate modules and the "admin" module got renamed to "operator" it would be great to reflect this change also in the oke package.  

update base module

```
  # admin server parameters
  oci_base_operator = local.oci_base_operator

  # bastion details
  oke_operator = local.oke_operator

...
```

**Comment by hyder** [comment]
Done in #166
