### ISSUE TITLE
Create cluster on existing VCN

### ISSUE THREAD

**Issue by livespotty** [oracle-terraform-modules/terraform-oci-oke#171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This new feature is to create oke cluster on existing vcn

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/docs/configuration.adoc#configure-oci-networking-parameters

When a VCN ocid is given the cluster is created on an existing VCN.

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by hyder** [comment]
Duplicate of #163. Consequently we are reopening it.

**Comment by karthicgit** [comment]
@livespotty

**Comment by livespotty** [comment]
Thank you @hyder  and @karthicgit . This feature was tested and it works as expected.

**Comment by hyder** [comment]
Thanks for taking the time to test @livespotty. We'll merge and include this in the next release.

**Comment by hyder** [comment]
Added in #175
