### ISSUE TITLE
Add schema for resource manager

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-oke#172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://docs.cloud.oracle.com/en-us/iaas/Content/ResourceManager/Concepts/terraformconfigresourcemanager.htm

**Comment by devoncrouse** [comment]
https://docs.oracle.com/en-us/iaas/Content/ResourceManager/Concepts/terraformconfigresourcemanager_topic-schema.htm

**Comment by devoncrouse** [comment]
Added examples to 5.x [user guide](https://oracle-terraform-modules.github.io/terraform-oci-oke) in https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/703
