### ISSUE TITLE
[Bug] Helm is needed when it shouldn't be

### ISSUE THREAD

**Issue by cawilliamson** [oracle-terraform-modules/terraform-oci-oke#18]
In your latest commit you seem to have broken the helm dependency.

I have no intentions of using Helm and am using the default of install_helm=false *but* the binary itself is now needed since the ~/.helm dir needs to exist in order for your TF code to execute.

**Comment by hyder** [comment]
Sorry about that. I actually misunderstood how the helm provider works. Also, I found an open bug on the helm provider yesterday. I'll look at your fix

**Comment by hyder** [comment]
Fixed in https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/29
