### ISSUE TITLE
public worker_mode fails to pull images from container-registry.oracle.com

### ISSUE THREAD

**Issue by guoyongzhang** [oracle-terraform-modules/terraform-oci-oke#183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
terraform 0.12.25
terraform-provider-oci_v3.85.0_x4
oracle-terraform-modules/oke/oci 2.2.2

### Affected Resource(s)

pods in the OKE cluster

### Description

We have been using private worker_mode terraforming our cluster and everything works well.  
I tried to to switch the worker_mode to public without changing anything else.  The cluster was provisioned.  However, the pods can not pull images from container-registry.oracle.com.  
Here is the output describing my test pod:
```
Events:
  Type     Reason     Age                From                Message
  ----     ------     ----               ----                -------
  Normal   Scheduled  89s                default-scheduler   Successfully assigned default/ocrtest-xfghn to 10.0.64.3
  Normal   BackOff    31s (x2 over 73s)  kubelet, 10.0.64.3  Back-off pulling image "container-registry.oracle.com/os/oraclelinux:7-slim"
  Warning  Failed     31s (x2 over 73s)  kubelet, 10.0.64.3  Error: ImagePullBackOff
  Normal   Pulling    18s (x3 over 88s)  kubelet, 10.0.64.3  Pulling image "container-registry.oracle.com/os/oraclelinux:7-slim"
  Warning  Failed     3s (x3 over 73s)   kubelet, 10.0.64.3  Failed to pull image "container-registry.oracle.com/os/oraclelinux:7-slim": rpc error: code = Unknown desc = Get https://container-registry.oracle.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     3s (x3 over 73s)   kubelet, 10.0.64.3  Error: ErrImagePull
```

**Comment by karthicgit** [comment]
@guoyongzhang 
       1. Are you able to pull the images directly from worker node. "Example command :docker pull
container-registry.oracle.com/os/oraclelinux:7-slim"
  
Since its a public image i think you are not using any secrets,please confirm.

**Comment by hyder** [comment]
I've replicated the issue. We'll need to review the public subnet configuration

**Comment by hyder** [comment]
Looks like there's a missing egress security rule
