### ISSUE TITLE
Deploy using ORM

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-oke#186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

1. Allow public ssh keys to be entered as text
2. Allow ssh keys on node pools to be optional
3. Upgrade base module
4. Providers don't need extra parameters

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by hyder** [comment]
#191

**Comment by devoncrouse** [comment]
Added examples to 5.x [user guide](https://oracle-terraform-modules.github.io/terraform-oci-oke) in https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/703
