### ISSUE TITLE
Can not create client, bad configuration: did not find a proper configuration for tenancy

### ISSUE THREAD

**Issue by noeldcosta** [oracle-terraform-modules/terraform-oci-oke#199]
Terraform plan gives the below errors. The error goes away if tenancy_ocid, user_ocid, fingerprint, private_key_path is manually added to the provider.tf (for ex: terraform-oci-oke\modules\policies\provider.tf)

[opc@tf-oke data]$ terraform version
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/oci v3.90.0
+ provider registry.terraform.io/hashicorp/template v2.1.2

[opc@tf-oke data]$ cat provider.tf 
provider "oci" {
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = var.region
  tenancy_ocid         = var.tenancy_id
  user_ocid            = var.user_id
}

[opc@tf-oke data]$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.oke.data.template_file.install_kubectl: Refreshing state...
module.base.module.operator.data.template_file.oracle_template[0]: Refreshing state...
module.base.module.bastion.data.template_file.autonomous_template[0]: Refreshing state...
module.oke.data.template_file.create_service_account[0]: Refreshing state...
module.oke.data.template_file.metricserver_enabled[0]: Refreshing state...
module.base.module.operator.data.template_file.oracle_cloud_init_file[0]: Refreshing state...
module.base.module.bastion.data.template_file.autonomous_cloud_init_file[0]: Refreshing state...
module.base.module.operator.data.template_cloudinit_config.operator[0]: Refreshing state...
module.base.module.bastion.data.template_cloudinit_config.bastion[0]: Refreshing state...
module.base.module.operator.data.oci_identity_tenancy.tenancy: Refreshing state...
module.base.module.bastion.data.oci_identity_availability_domains.ad_list: Refreshing state...
module.base.data.oci_identity_tenancy.tenancy: Refreshing state...
module.policies.data.oci_identity_tenancy.tenancy: Refreshing state...
module.base.module.vcn.data.oci_core_services.all_oci_services[0]: Refreshing state...
module.oke.data.oci_core_images.latest_images["np1"]: Refreshing state...
module.oke.data.oci_core_images.latest_images["np2"]: Refreshing state...
module.base.module.operator.data.oci_identity_availability_domains.ad_list: Refreshing state...
module.base.module.bastion.data.oci_core_images.autonomous_images: Refreshing state...
module.base.data.oci_identity_availability_domains.ad_list: Refreshing state...
module.base.module.operator.data.oci_core_images.oracle_images: Refreshing state...
module.base.module.bastion.data.oci_identity_tenancy.tenancy: Refreshing state...
module.network.data.oci_core_services.all_oci_services: Refreshing state...
module.base.data.template_file.ad_names[1]: Refreshing state...
module.base.data.template_file.ad_names[0]: Refreshing state...
module.base.data.template_file.ad_names[2]: Refreshing state...
module.policies.data.oci_identity_regions.home_region: Refreshing state...
module.base.module.operator.data.template_file.ad_names[0]: Refreshing state...
module.base.module.operator.data.template_file.ad_names[2]: Refreshing state...
module.base.module.operator.data.template_file.ad_names[1]: Refreshing state...
module.base.module.operator.data.oci_identity_regions.home_region: Refreshing state...
module.base.module.bastion.data.template_file.ad_names[1]: Refreshing state...
module.base.module.bastion.data.template_file.ad_names[0]: Refreshing state...
module.base.module.bastion.data.template_file.ad_names[2]: Refreshing state...
module.oke.data.template_file.helm_enabled[0]: Refreshing state...
module.base.data.oci_identity_regions.home_region: Refreshing state...
module.base.module.bastion.data.oci_identity_regions.home_region: Refreshing state...

------------------------------------------------------------------------

Error: can not create client, bad configuration: did not find a proper configuration for tenancy

  on modules/policies/provider.tf line 5, in provider "oci":
   5: provider "oci" {

Error: can not create client, bad configuration: did not find a proper configuration for tenancy

  on .terraform/modules/base.bastion/terraform-oci-bastion-1.0.6/ons.tf line 4, in provider "oci":
   4: provider "oci" {

Error: can not create client, bad configuration: did not find a proper configuration for tenancy

  on .terraform/modules/base.operator/terraform-oci-operator-1.0.12/instance_principal.tf line 5, in provider "oci":
   5: provider "oci" {

**Comment by noeldcosta** [comment]
The errors go away after installing OCI CLI.

**Comment by hyder** [comment]
Thanks for logging this issue. Based on our tests, the problem arises if the oci cli is not installed and not configured. This dependency was introduced in the 2.3.0 released when we were preparing to add support for Resource Manager. 

The interim solution would be to install and configure the oci client on the host where Terraform is running. Either we make this 
However, this would introduce a dependency on installing the oci cli. Either we make this become part of the prerequisites or we reverse this change in master but keep it in a separate branch for Resource Manager.

@Djelibeybi @markxnelson What do you think?
