### ISSUE TITLE
Granular control on deploying instances in node pools in specific ADs

### ISSUE THREAD

**Issue by noeldcosta** [oracle-terraform-modules/terraform-oci-oke#201]
Would be good to implement support to deploy multiple instances to a single AD/ subset of ADs which is possible via the Cloud Console. 

At present a definition like below would round-robin across the ADs instead of deploying both VMs in the same AD.

node_pools = {
  np1 = ["VM.Standard2.8", 2]
  np2 = ["VM.Standard2.4", 2]
}

Perhaps a definition like this would help define np1 to span across AD1 and AD2 while np2 will deploy 2 instances in AD1

node_pools = {
  np1 = ["VM.Standard2.8", "AD1, AD2", 2]
  np2 = ["VM.Standard2.4", "AD1", 2]
}

**Comment by pradeep-gangappa** [comment]
@hyder 
I'm planning to look into this , shall I proceed to make outlined methods 

Reason we need AD specific nodes ,there are few application which need all pool nodes need to be in same AD as part of performance. 
and there is limitation of few team who have access to specific AD in both the cases current module lags the feature

**Comment by hyder** [comment]
Sure. Please work with @karthicgit as he did the initial work on the above data structure. 

Also, note in this [PR](https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/208/files), I'm planning to use the 3rd element as custom boot size. So, for specific AD placement, ensure you use the 4th element. 

Also note when you add the code for specific AD placement, this should be in the event a preferred AD is specified. If not specified, then the worker nodes should be across all 3 ADs as is currently the case.

Thanks for your contribution. Looking forward to it!

**Comment by pradeep151287** [comment]
@hyder yeah I have noted PR and made AD as 4th parameter to nodepool 

Code changes are done and tested its working as expected. 
1. if AD values are provided like "AD1, AD2" it will span across the given AD, if an empty list "" then it will span across all the subnets in the region. 

@karthicgit 
you can review pull request and suggest if any changes required.

**Comment by pradeep-gangappa** [comment]
@hyder yeah I have noted PR and made AD as 4th parameter to nodepool

Code changes are done and tested its working as expected.

if AD values are provided like "AD1, AD2" it will span across the given AD, if an empty list "" then it will span across all the subnets in the region.
@karthicgit
you can review pull request and suggest if any changes required.

**Comment by hyder** [comment]
I'm closing this due to lack of response. When you are ready to work on it again, please reopen.

**Comment by pradeep151287** [comment]
I have given my changes already if any changes needed let me know, I think in our last discussion you mentioned these changes not required so you're not merging changes.
