### ISSUE TITLE
I can't find any documentation for using terraform directly to create from registry images on a cluster

### ISSUE THREAD

**Issue by jstanbri** [oracle-terraform-modules/terraform-oci-oke#215]
Terraform **Oracle Cloud Infrastructure** OKE module.

I expected to be able to build terraform script to set up my clusters, and build from images in the OCIR - however, all the documentation I can find, suggests that the only method OCI supports is to create a bastion server and then create kubctl to implement with a yaml file, and not from terraform directly?

Is this a deliberate choice / architecture from Oracle, or just, this is as far as we've got , and that functionality is still to come? - or, I've just missed something (I'd be really happy with that as the outcome!)

**Comment by hyder** [comment]
Hi,

Thanks for your question.

This community project's purpose is mainly to facilitate building OKE clusters and we use Terraform for that. We take an opinionated approach while keeping the project as lean as possible e.g. we add kubectl, helm to facilitate k8s admin's tasks. We think this facilitates reuse and encourages adoption.

Regarding usage of OCIR, there is an option that automates the integration with OCIR: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/docs/configuration.adoc#configure-ocir-parameters. This will create a secret in the OKE cluster which you can then use as imagePullSecrets in your deployment. You can then write your yamls and run kubectl e.g. via null_resource+local_exec.

If your question is about using the [terraform kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) with the OKE cluster, then absolutely you can do that too. You need to configure the kubernetes provider and then create the relevant resources see [an example with helm](https://medium.com/oracledevs/extending-terraform-oke-with-a-helm-chart-a51ae0df29d4). Whichever way you do it e.g. yaml (locally/remotely) or terraform is up to you. 

Regardless of using kubectl+yamls or the terraform provider, if you wish to pull an image from OCIR and your OCIR repo is protected, then you need to reference the imagePullSecrets in your deployment object. You can choose to create it manually or take advantage of automating it.

Finally, we are always striving to improve the features and documentation. If you have an interesting idea or you feel the documentation is lacking, we would love to hear from you. Please submit a feature request. We also welcome contributions from the community.

**Comment by jstanbri** [comment]
Thanks so much, that is really useful response and will look at that automated integration for our projects.
