### ISSUE TITLE
Add support for VM.Standard.E3.Flex in node pool

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-oke#216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)
in resource **nodepools**

if shape is E3.flex, add 

    node_shape_config {

        #Optional
        ocpus = "${var.node_pool_node_shape_config_ocpus}"
    }

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by hyder** [comment]
added in #217

**Comment by pirat8** [comment]
Is it also possible to configure the memory node_shape_config? This would be the real benefit of using flexible shapes.

**Comment by hyder** [comment]
> Is it also possible to configure the memory node_shape_config? This would be the real benefit of using flexible shapes.

At the moment, while the instance api supports memory customization for the E3 flex shape, the node pool api does not. We have submitted an enhancement request here with the provider team: https://github.com/terraform-providers/terraform-provider-oci/issues/1197 

We'll add this once the node pool api supports it.

**Comment by hyder** [comment]
I've added it as a new issue here: https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/234
