### ISSUE TITLE
Creating oci_identity_dynamic_group resource fails with error

### ISSUE THREAD

**Issue by styledigger** [oracle-terraform-modules/terraform-oci-oke#222]
Hi,
I'm referencing terraform-oci-oke module as a remote module in my terraform script. Most of the resources is created fine, but the script fails with:

```
Error: did not find a proper configuration for private key

  on .terraform\modules\oke.base.operator\instance_principal.tf line 10, in resource "oci_identity_dynamic_group" "operator_instance_principal":
  10: resource "oci_identity_dynamic_group" "operator_instance_principal" {
```
Not sure whether this is about API key or SSH key, but I suppose it is the API key. As I said, all the other resources got created, so the API key was successfully loaded and did authenticate to OCI just fine. 
Any Idea what does this error actually mean?

Thanks in advance
Marian

**Comment by hyder** [comment]
This should be the api key. It looks like your home provider is not properly initialized. https://github.com/oracle-terraform-modules/terraform-oci-operator/blob/master/instance_principal.tf

**Comment by hyder** [comment]
@styledigger Can we close this or is it still a problem?

**Comment by hyder** [comment]
I'm closing this. If you're still having a problem, please reopen.
