### ISSUE TITLE
Ability to use proxy

### ISSUE THREAD

**Issue by alogoc** [oracle-terraform-modules/terraform-oci-oke#223]
There are cases where access to internet is blocked unless accessed by a proxy, and thus installation of helm and metric server is not possible in this environment.

Proposing the ability to define the http/https proxy as variables on terraform.tfvars  which will be parsed to systemd docker, as well as during the installation of helm as environment variables.

**Comment by hyder** [comment]
kubectl and helm are executed on the remote operator host on OCI, not locally. See here: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/docs/instructions.adoc#adding-the-operator-host

**Comment by hyder** [comment]
hi @alogoc, can you please elaborate? If not, we'll close this issue.

**Comment by hyder** [comment]
Closing the issue. Please reopen if you are still having problems
