### ISSUE TITLE
many exception for yum update

### ISSUE THREAD

**Issue by davinwei** [oracle-terraform-modules/terraform-oci-oke#233]
when i execute the terraform apply , and got following exception:
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:22 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Running, pid: 11501
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 184 M RSS (513 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:24 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Running, pid: 11501
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 184 M RSS (513 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:26 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Running, pid: 11501
module.oke.null_resource.install_kubectl_operator[0]: Still creating... [1m40s elapsed]
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 184 M RSS (513 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:28 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Running, pid: 11501
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 184 M RSS (513 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:30 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Running, pid: 11501
module.oke.oci_containerengine_cluster.k8s_cluster: Still creating... [2m30s elapsed]
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 184 M RSS (513 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:32 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Running, pid: 11501
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 190 M RSS (517 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:34 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Running, pid: 11501
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 208 M RSS (535 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:36 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Running, pid: 11501
module.oke.null_resource.install_kubectl_operator[0]: Still creating... [1m50s elapsed]
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 176 M RSS (501 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:38 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Sleeping, pid: 11501
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other application is: yum
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Memory : 176 M RSS (501 MB VSZ)
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     Started: Wed Nov  4 11:56:43 2020 - 00:40 ago
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):     State  : Sleeping, pid: 11501
module.oke.oci_containerengine_cluster.k8s_cluster: Still creating... [2m40s elapsed]
module.oke.null_resource.install_kubectl_operator[0] (remote-exec): Another app is currently holding the yum lock; waiting for it to exit...
module.oke.null_resource.install_kubectl_operator[0] (remote-exec):   The other appl

any comments for this issue? thanks

**Comment by hyder** [comment]
That's cloud-init installing some packages or doing updates. By default, the operator host will update all the yum packages and this is recommended. However, if you're in a hurry, you can turn this off by setting  ```operator_package_upgrade=false```.

**Comment by davinwei** [comment]
thanks

**Comment by hyder** [comment]
Did it solve your problem?
