### ISSUE TITLE
issue with the ssh proxy jump command generated by the tf scripts

### ISSUE THREAD

**Issue by eugsim1** [oracle-terraform-modules/terraform-oci-oke#246]
Hello
I m getting this output from the tf execution :
the private key is wls-wdt-testkey-priv.txt 
Outputs:

```
bastion_public_ip = 193.123.33.61
ig_route_id = ocid1.routetable.oc1.eu-amsterdam-1.aaaaaaaafh7zup54yze7p5ddjwyyog5mkk6ailthr7weubcwlgcakew26jca
kubeconfig = export KUBECONFIG=generated/kubeconfig
nat_route_id = ocid1.routetable.oc1.eu-amsterdam-1.aaaaaaaajnrxn6m43hmxjtxr7dsg3cmglouyppwml6wwkrh5r65x7u63g54q
operator_private_ip = 10.0.1.10
ssh_to_bastion = ssh -i wls-wdt-testkey-priv.txt opc@193.123.33.61
ssh_to_operator = ssh -i wls-wdt-testkey-priv.txt -J opc@193.123.33.61 opc@10.0.1.10
```

the ssh to the operator fails 
```
 ssh -i wls-wdt-testkey-priv.txt -J opc@193.123.33.61 opc@10.0.1.10
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
ssh_exchange_identification: Connection closed by remote host
```
The variation below works however :
```
ssh -i wls-wdt-testkey-priv.txt -o ProxyCommand="ssh -i wls-wdt-testkey-priv.txt -W %h:%p  opc@193.123.33.61"  opc@10.0.1.10
Last login: Sat Dec  5 02:16:40 2020 from bastion.bastion.oke.oraclevcn.com
```
What would be the reason that the generated ssh command with the jump flag fails in both cases i m using the same private key from the same location with the -J the ssh fails with the old syntax everything is ok !

**Comment by hyder** [comment]
-J is a [simpler form of ProxyCommand](https://medium.com/maverislabs/proxyjump-the-ssh-option-you-probably-never-heard-of-2d7e41d43464) and introduced in openssh 7.3 (I think). Your ssh client might be older version and hence not supporting -J but ProxyCommand still works.

**Comment by hyder** [comment]
Closing this issue. Feel free to reopen it if you think this needs further investigation

**Comment by cwiggs** [comment]
I had this same issue as well, it seems the `-i` doesn't pass to the jumphost properly when using `-J`.  I'm also running a new version of openssh so I don't think that is the issue.

```
OpenSSH_9.2p1 Debian-2, OpenSSL 3.0.8 7 Feb 2023
```

**Comment by hyder** [comment]
ssh assumes some defaults e.g. in $HOME/.ssh/id_rsa. If you're using its defaults, then things work fine. The problem arises when you've kept your key somewhere else or you've named it differently. You can see this by adding a -v or -vv you'll see the ssh trying its defaults and then failing. The key is actually correctly passed to the jumphost but not to the operator.  So, you need to add it to your ssh-agent: 

```
eval "$(ssh-agent -s)"
ssh-add /path/to/privatekey
```

Then run ssh to the operator or other hosts again.

**Comment by cwiggs** [comment]
Another option is to simple use a command like this:

```
ssh -i ./private_key -o ProxyCommand='ssh -i ./private_key -W %h:%p opc@${bastion_host}' opc@${operator_host}
```

Should the terraform be updated to use this command over the shorthand `-J` ?

**Comment by hyder** [comment]
Please send us a PR :)

**Comment by cwiggs** [comment]
PR sent :)

**Comment by rodrigc** [comment]
@cwiggs @hyder @devoncrouse I think this fix needs to be ported to the [5.x](https://github.com/oracle-terraform-modules/terraform-oci-oke/tree/5.x) branch?
