### ISSUE TITLE
data.oci_core_images.autonomous_images.images is null

### ISSUE THREAD

**Issue by webadmininc** [oracle-terraform-modules/terraform-oci-oke#247]
To whom,

I am using terraform .0.13.5 and clone the git repo.

when I run terraform plan, 
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.oke.data.template_file.install_kubectl: Refreshing state...
module.base.module.operator.data.template_file.oracle_template[0]: Refreshing state...
module.base.module.bastion.data.template_file.autonomous_template[0]: Refreshing state...
module.base.module.bastion.data.template_file.autonomous_cloud_init_file[0]: Refreshing state...
module.base.module.operator.data.template_file.oracle_cloud_init_file[0]: Refreshing state...
module.base.module.bastion.data.template_cloudinit_config.bastion[0]: Refreshing state...
module.base.module.operator.data.template_cloudinit_config.operator[0]: Refreshing state...
module.base.module.operator.data.oci_core_images.oracle_images: Refreshing state...
module.network.data.oci_core_services.all_oci_services: Refreshing state...
module.base.module.vcn.data.oci_core_services.all_oci_services[0]: Refreshing state...
module.oke.data.oci_core_images.latest_images["np2"]: Refreshing state...
module.oke.data.oci_core_images.latest_images["np3"]: Refreshing state...
module.oke.data.oci_core_images.latest_images["np1"]: Refreshing state...
module.base.module.operator.data.oci_identity_availability_domains.ad_list: Refreshing state...
module.policies.data.oci_identity_tenancy.tenancy: Refreshing state...
module.base.module.operator.data.oci_identity_tenancy.tenancy: Refreshing state...
module.base.module.bastion.data.oci_core_images.autonomous_images: Refreshing state...
module.base.module.bastion.data.oci_identity_availability_domains.ad_list: Refreshing state...
module.base.module.bastion.data.oci_identity_tenancy.tenancy: Refreshing state...
module.base.data.oci_identity_availability_domains.ad_list: Refreshing state...
module.base.data.oci_identity_tenancy.tenancy: Refreshing state...
module.policies.data.oci_identity_regions.home_region: Refreshing state...
module.base.module.operator.data.template_file.ad_names[2]: Refreshing state...
module.base.module.operator.data.template_file.ad_names[1]: Refreshing state...
module.base.module.operator.data.template_file.ad_names[0]: Refreshing state...
module.base.module.operator.data.oci_identity_regions.home_region: Refreshing state...
module.base.data.template_file.ad_names[1]: Refreshing state...
module.base.data.template_file.ad_names[2]: Refreshing state...
module.base.data.template_file.ad_names[0]: Refreshing state...
module.base.module.bastion.data.oci_identity_regions.home_region: Refreshing state...
module.base.module.bastion.data.template_file.ad_names[1]: Refreshing state...
module.base.module.bastion.data.template_file.ad_names[0]: Refreshing state...
module.base.module.bastion.data.template_file.ad_names[2]: Refreshing state...
module.oke.data.template_file.install_helm[0]: Refreshing state...
module.base.data.oci_identity_regions.home_region: Refreshing state...

Error: Attempt to index null value

  on .terraform/modules/base.bastion/locals.tf line 13, in locals:
  13:   bastion_image_id = var.bastion_image_id == "Autonomous" ? data.oci_core_images.autonomous_images.images.0.id : var.bastion_image_id
    |----------------
    | data.oci_core_images.autonomous_images.images is null

This value is null, so it does not have any indices.

Error: Attempt to index null value

  on .terraform/modules/base.operator/locals.tf line 13, in locals:
  13:   operator_image_id = var.operator_image_id == "Oracle" ? data.oci_core_images.oracle_images.images.0.id : var.operator_image_id
    |----------------
    | data.oci_core_images.oracle_images.images is null

This value is null, so it does not have any indices.

**Comment by webadmininc** [comment]
tfvars
###############################
# Identity and access parameters
###############################
api_fingerprint = "d8:68:9bxxxxxxxxxxxx"
api_private_key_path = "/Users/xxxxxxxxxx.pem"
region = "us-phoenix-1"
tenancy_id = "ocid1.tenancy.xxxxxxxxxxxxxxx"
user_id = "ocid1.user.oc1..axxxxxxxxxxxxx"
###############################
# compartments parameters
###############################

compartment_id = "ocid1.compartment.oc1..aaaxxxxxxxxxxxxxxxxq"
label_prefix = "dev"
# ssh keys
ssh_private_key_path = "/Users/xxxxxxxxxxx/mysshkey"
ssh_public_key_path = "/Users/xxxxxxxxxxxx/mysshkey.pub"

###############################
# networking
###############################




# ocir
email_address = ""
secret_id = "none"
secret_name = "ocirsecret"
tenancy_name = ""
username = ""
existing_key_id = ""

admin_enabled = true
admin_image_id = "NONE", also Tried Autonomous
admin_instance_principal = true
admin_notification_enabled = true
admin_notification_endpoint = "mxxxxxxxx"
admin_notification_protocol = "EMAIL"
admin_notification_topic = "admin_server_notification"
admin_package_upgrade = true
admin_shape = "VM.Standard.E2.1"
admin_timezone = "America/Los_Angeles"

**Comment by webadmininc** [comment]
if I replace 

bastion_image, operator_image and node_image with specific image id
say ->
ocid1.image.oc1.phx.aaaaaaaaxdnx3den32vwplngpeu44zakw7lxup7vcdd3jmke4pfleaug3m6q

terraform plan
Error: Invalid index

  on .terraform/modules/base.bastion/datasources.tf line 66, in data "template_cloudinit_config" "bastion":
  66:     content      = data.template_file.autonomous_cloud_init_file[0].rendered
    |----------------
    | data.template_file.autonomous_cloud_init_file is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/base.operator/datasources.tf line 63, in data "template_cloudinit_config" "operator":
  63:     content      = data.template_file.oracle_cloud_init_file[0].rendered
    |----------------
    | data.template_file.oracle_cloud_init_file is empty tuple

The given key does not identify an element in this collection value.

**Comment by hyder** [comment]
Hi,

Thanks for logging this issue. Can you please check if you can create an instance of Autonomous Linux from the OCI console? Also, for operator and node pools, use Oracle 7 only.

**Comment by webadmininc** [comment]
Hyder, thank you for looking at this case.

I can provision an Autonomous Linux Version from the console.
Image: Oracle-Autonomous-Linux-7.9-2020.12-0.

For the BastionHost, I used Oracle-Autonomous-Linux-7.9-2020.12-0
Image_id = ocid1.image.oc1.phx.aaaaaaaazwululyfmkhtctbr6jfgjnpq3oyi53hoqy4xkv2o7h4bcww2bv6a

Operator and Nodes
Oracle-Linux-7.9-2020.11.10-1
image_id =ocid1.image.oc1.phx.aaaaaaaaxdnx3den32vwplngpeu44zakw7lxup7vcdd3jmke4pfleaug3m6q

terraform plan,
Error: Invalid index

  on .terraform/modules/base.bastion/datasources.tf line 66, in data "template_cloudinit_config" "bastion":
  66:     content      = data.template_file.autonomous_cloud_init_file[0].rendered
    |----------------
    | data.template_file.autonomous_cloud_init_file is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/base.operator/datasources.tf line 63, in data "template_cloudinit_config" "operator":
  63:     content      = data.template_file.oracle_cloud_init_file[0].rendered
    |----------------
    | data.template_file.oracle_cloud_init_file is empty tuple

The given key does not identify an element in this collection value.

**Comment by hyder** [comment]
May I know how you're using the repo? Cloning or a particular release?  I see you're using some of these parameters:

`admin_enabled = true
admin_image_id = "NONE", also Tried Autonomous
admin_instance_principal = true
admin_notification_enabled = true`

We've renamed these to operator quite a while ago. So they should be `operator_enabled`, `operator_image_id` etc. See: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/docs/terraformoptions.adoc#admin-host

Please let us know if this solves the problem.

**Comment by hyder** [comment]
Closing due to lack of response. Please reopen if this is still a problem.
