### ISSUE TITLE
Support api_private_key_password

### ISSUE THREAD

**Issue by rbair23** [oracle-terraform-modules/terraform-oci-oke#250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In my terraform scripts, I use an API private key that includes a passphrase. The OCI provider has an attribute "private_key_password" which is used to set this. I don't seem to have something similar on the OKE module. I expected to find "api_private_key_password", but this resulted in an error.

**Comment by hyder** [comment]
As in #249, this is configured in your provider. You can choose to add it as as variable if you want to load it through a variable file/environment variabl.

**Comment by hyder** [comment]
https://www.terraform.io/upgrade-guides/0-14.html#sensitive-values-in-plan-output

**Comment by hyder** [comment]
Closed in #372
