### ISSUE TITLE
need to support flexible Load Balancer 

### ISSUE THREAD

**Issue by davinwei** [oracle-terraform-modules/terraform-oci-oke#256]
now OCI team just released the flexible load balancer, does this scrip support this feature? thanks

**Comment by hyder** [comment]
OKE doesn't support it yet. We'll add it - when the following happens:
- the OKE service supports it
- the API supports it
- the terraform oci provider supports it

We'll keep this issue open as a future enhancement request.

**Comment by karthicgit** [comment]
@davinwei Flexible Loadbalancer is available now in OKE using the annotation.
service.beta.kubernetes.io/oci-load-balancer-shape: flexible
service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: <min-value>
service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: <max-value>

**Comment by hyder** [comment]
We'll add this in the docs and close the issue.
