### ISSUE TITLE
Add a separate unmanaged node pool to run cluster autoscaler

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-oke#273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
 OKE now supports cluster autoscaler: https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm. We need to add support for it like we have done for horizontal and vertical pod autoscalers.

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by shapeofarchitect** [comment]
Its very critical to add the support for auto-scalar to increase the adoption for enterprise customers , I would appreciate timelines please ?

**Comment by hyder** [comment]
Hi @shapeofarchitect, 

Thanks for reaching out. We have some ideas but we haven't fully tested them yet. We will probably look into this after the 4.0 release.

**Comment by mschmidt291** [comment]
Any updates on this?

**Comment by aibarbetta** [comment]
Hi @hyder, any updates on this? I'm currently using this module with the cluster autoscaler installed, the autoscaler changes generate a differences in the terraform plan, is there any suggested workaround?

**Comment by hyder** [comment]
Hi @aibarbetta 

I think we'll be able to start implementing this once #562 is complete. Would you be interested in testing?

**Comment by aibarbetta** [comment]
> Hi @aibarbetta
> 
> I think we'll be able to start implementing this once #562 is complete. Would you be interested in testing?

@hyder sure, I can help test the changes in my environment, mention me in the PR when it's ready to test

**Comment by hyder** [comment]
After further experiments, we'll add support for this gradually:

1. A separate unmanaged node pool to run cluster autoscaler
2. IAM resources (tags, dynamic group, policies) for the worker nodes that will be running cluster autoscaler
3. Deploying cluster autoscaler itself. 

As such, I'm renaming this issue to add the unmanaged node pool for cluster autoscaler. We'll also create a new dedicated milestone for adding cluster autoscaler support.

**Comment by hyder** [comment]
@aibarbetta @mschmidt291 @shapeofarchitect

**Comment by dontbreakit** [comment]
hi @hyder, not sure where is the proper place to ask, here or in #579 

Is it possible just to add the following snippet to `modules/oke/nodepools.tf`?
```terraform
  lifecycle {
    ignore_changes = [
      node_config_details[0].size
    ]
  }
``` 
Lots of ppl don't use the whole module, rather only a few submodules( `modules/oke` in our case), and it would solve the issue where Terraform needs to reconcile changes made by cluster-autoscaler (installed simply with Helm)

**Comment by hyder** [comment]
@devoncrouse can you please look into this?

**Comment by 12345ieee** [comment]
This was affected by https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/624 , before that the whole object (including size) was ignored.

The issue with adding the ignore is that it's not possible to change the size anymore after creation, effectively changing the `size` parameter into an `initial_size`.

If this is the intended way to do things, I'll look into installing the autoscaler and stop managing the size via terraform.
