### ISSUE TITLE
Terraform plan/apply fails if there is no match for node_pool_os_version

### ISSUE THREAD

**Issue by styledigger** [oracle-terraform-modules/terraform-oci-oke#281]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/oci v4.16.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)
`node_pool_image_id` local variable in modules/oke/locals.tf

### Terraform Configuration Files

```hcl
...
node_pool_os_version = "7.8"
...
```

### Debug Output

```
      - .sources[0].image_id: was cty.StringVal("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaawx7h4vxjmrgha6inypi7df63q2y3bjylrp24b4sbgekumq5pqc7a"), but now cty.StringVal("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa62zux7w2njw7yyhjcwydpuzhbi2iavnhm4lwbruthl6b5htjlkyq")
      - .sources[0].source_name: was cty.StringVal("Oracle-Linux-7.9-2021.02.16-0"), but now cty.StringVal("Oracle-Linux-7.9-2021.03.17-0")
      - .sources[1].source_name: was cty.StringVal("Oracle-Linux-7.9-2021.01.12-0"), but now cty.StringVal("Oracle-Linux-7.9-2021.02.16-0")
      - .sources[1].image_id: was cty.StringVal("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa5w2lrmsn6wpjn7fbqv55curiarwsryqhoj4dw5hsixrl37hrinja"), but now cty.StringVal("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaawx7h4vxjmrgha6inypi7df63q2y3bjylrp24b4sbgekumq5pqc7a")
      - .sources[2].image_id: was cty.StringVal("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaxv7ekktzkq6kyvsz32ofi3jrvdru7nan7vj3fbwfgairtbvihhkq"), but now cty.StringVal("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa5w2lrmsn6wpjn7fbqv55curiarwsryqhoj4dw5hsixrl37hrinja")
      - .sources[2].source_name: was cty.StringVal("Oracle-Linux-7.9-2020.12.16-0"), but now cty.StringVal("Oracle-Linux-7.9-2021.01.12-0")
      - .sources[3].source_name: was cty.StringVal("Oracle-Linux-7.8-2020.05.26-0"), but now cty.StringVal("Oracle-Linux-7.6")
      - .sources[3].image_id: was cty.StringVal("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaafjcegvwbd3qgin4unmtr5jm5gjhtcfxgnhjwodzewlja5zqm6eaq"), but now cty.StringVal("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaazfzlw2infpo3svzjgrcl237xsbod4l5yuzfpqdqmmawia2womz5q")
      - .sources: element 4 has vanished

      ...
      
2021/04/16 10:08:46 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
Error: Error in function call

  on modules/oke/locals.tf line 23, in locals:
  23:   node_pool_image_id = element([for source in data.oci_containerengine_node_pool_option.node_pool_options.sources : source.image_id if length(regexall(var.node_pools.node_pool_os_version, source.source_name)) > 0], 0)
    |----------------
    | data.oci_containerengine_node_pool_option.node_pool_options.sources is list of object with 4 elements
    | var.node_pools.node_pool_os_version is "7.8"

Call to function "element" failed: cannot use element function with an empty
list.
```

### Expected Behavior

If there is no match for requested OS  version, one of available versions should be selected, but the script should not fail. 
In my case, I was running `terraform plan` on infrastructure created just 3 weeks ago. There were no changes since, but the script failed anyway.

### Actual Behavior

What happened is that there is no requested OS version (7.8) in the list of available images returned by `data.oci_containerengine_node_pool_option.node_pool_options.sources` and therefore the element function fails. 

### Steps to Reproduce

Set `node_pool_os_version = "7.8"` in terraform.tfvars and run `terraform apply`
My region is set to eu-frankfurt-1 so it is probably worth setting this as well. I did not try different region.

**Comment by karthicgit** [comment]
@styledigger we have updated the default node_pool_os_version to 7.9 in terraform.tfvars.example. Oracle Linux 7.8 is not available so the plan/apply will fail. Please change the node_pool_os_version to 7.9 or higher.

**Comment by styledigger** [comment]
Thank you @karthicgit, I did already change the version to 7.9 and the error has gone. My point is that terraform script should not fail this way. It took me over an hour to diagnose the issue. And the same will happen again once we move to 8.0.
My suggestion is to automatically choose one oft he available versions if there is no match....

**Comment by karthicgit** [comment]
@styledigger Sure. we will add a validation as a first step .
