### ISSUE TITLE
map is deprecated, not available in terraform 0.15

### ISSUE THREAD

**Issue by dirgapeter** [oracle-terraform-modules/terraform-oci-oke#283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.15.0

+ provider registry.terraform.io/hashicorp/oci v4.21.0

### Affected Resource(s)

output "subnet_ids"

### Expected Behavior

`terraform apply` with success

### Actual Behavior

There is error: 

```
 Error: Error in function call
│ 
│   on .terraform/modules/oke_network/modules/okenetwork/outputs.tf line 5, in output "subnet_ids":
│    5:   value = map(
│    6:     "cp", join(",", oci_core_subnet.cp[*].id),
│    7:     "workers", join(",", oci_core_subnet.workers[*].id),
│    8:     "int_lb", join(",", oci_core_subnet.int_lb[*].id),
│    9:     "pub_lb", join(",", oci_core_subnet.pub_lb[*].id)
│   10:   )
│     ├────────────────
│     │ oci_core_subnet.cp will be known only after apply
│     │ oci_core_subnet.int_lb will be known only after apply
│     │ oci_core_subnet.pub_lb will be known only after apply
│     │ oci_core_subnet.workers will be known only after apply
│ 
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use tomap({ ... }) syntax to write a literal map.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by hyder** [comment]
Hi @dirgapeter 

Thanks for bringing this to our attention. We haven't tested on v0.15 yet but we'll start doing so as soon as possible.
