### ISSUE TITLE
400-InvalidParameter for node image

### ISSUE THREAD

**Issue by guoyongzhang** [oracle-terraform-modules/terraform-oci-oke#289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform 0.14.10
hashicorp/oci v4.22.0
oracle-terraform-modules/oke/oci 3.1.0

### Affected Resource(s)

on .terraform/modules/oke/modules/oke/nodepools.tf line 4, in resource "oci_containerengine_node_pool" "nodepools":
   4: resource "oci_containerengine_node_pool" "nodepools" {

### Terraform Configuration Files

https://github.com/verrazzano/verrazzano/blob/master/tests/e2e/config/scripts/terraform/cluster/VM.Standard2.4-2.tfvars

node_pools = {
  "np1" = {
    shape = "VM.Standard2.4",
    node_pool_size = 4,
    boot_volume_size = 50
  }
}

### Debug Output

Error: 400-InvalidParameter 
Provider version: 4.22.0, released on 2021-04-14.  
Service: Containerengine Node Pool 
Error Message: the image ocid1.image.oc1.iad.aaaaaaaahukmiw6fbgy7p7ger755tzyxiwnr53thtsczgmdb4aceogfmn3cq may not exist or you are not authorized to access it, or nodeShape VM.Standard2.4 is not compatible with image ocid1.image.oc1.iad.aaaaaaaahukmiw6fbgy7p7ger755tzyxiwnr53thtsczgmdb4aceogfmn3cq 
OPC request ID: 68d828bcea93966a7fad3fd56d725033/198FFFB6A7F9A0F40C2DDD342C933F02/1FD2A2EA464B4F758ECF903AAD86AF5F 
Suggestion: Please update the parameter(s) in the Terraform config as per error message the image ocid1.image.oc1.iad.aaaaaaaahukmiw6fbgy7p7ger755tzyxiwnr53thtsczgmdb4aceogfmn3cq may not exist or you are not authorized to access it, or nodeShape VM.Standard2.4 is not compatible with image ocid1.image.oc1.iad.aaaaaaaahukmiw6fbgy7p7ger755tzyxiwnr53thtsczgmdb4aceogfmn3cq

  on .terraform/modules/oke/modules/oke/nodepools.tf line 4, in resource "oci_containerengine_node_pool" "nodepools":
   4: resource "oci_containerengine_node_pool" "nodepools" {

### Expected Behavior

The OKE cluster provisioned.

### Actual Behavior

The OKE cluster creation failed.

### Steps to Reproduce

The terraform configuration files are located here https://github.com/verrazzano/verrazzano/tree/master/tests/e2e/config/scripts/terraform/cluster.

### Important Factoids

This error only occurs in us-ashburn-1 region when creating v1.18.10 OKE cluster.  We had no problem terraforming with exactly same configuration in regions like eu-frankfurt-1, eu-zurich-1, ap-melbourne-1 , ca-montreal-1, ap-sydney-1 etc. 
We specify the shape (VM.Standard2.4) in the node pool, but not the image.

**Comment by karthicgit** [comment]
@guoyongzhang Could you please change the node_pool_os_version variable to 7.9 instead of  "7.8" and see that solves the issue.

**Comment by karthicgit** [comment]
Had a discussion with GZ it seems in ashburn region the top listed image is for ARM  which is different from other region.

**Comment by hyder** [comment]
@guoyongzhang , have you been able to use the `node_pool_image_id` instead? Please let us know if this is still an issue

**Comment by guoyongzhang** [comment]
The root cause https://jira.oci.oraclecorp.com/browse/OKE-15061 is marked 'done'.  I am testing it.

**Comment by guoyongzhang** [comment]
us-ashburn-1 is working again.

**Comment by karthicgit** [comment]
Reopening this issue as the node_pool_image is taking GPU image id instead of standard vm shape image id

**Comment by guoyongzhang** [comment]
This issue only affects v1.19.7.  v1.18.10 still works.

**Comment by guoyongzhang** [comment]
Starting just now, v1.18.10 stopped working at ap-seoul-1, ca-montreal-1.  It probably true for all regions.  `node-pool-options` list the image like `"Oracle-Linux-7.9-aarch64-2021.05.17-0"` as the first one.

**Comment by hyder** [comment]
I think this could be due to Arm just being GAed for OKE too: https://blogs.oracle.com/cloud-infrastructure/oracle-container-engine-for-kubernetes-oke-support-for-arm-based-instances-is-now-generally-available

**Comment by agv426** [comment]
I'm assuming a last resort workaround would be to limiting our OKE region usage to 1 region and specifying an exact image OCID to use until things are resolved.

Is there a better way that we can workaround this for now that will work with multiple regions?

thanks

**Comment by agv426** [comment]
we worked around this for now by providing the exact image ocid for every region

**Comment by hyder** [comment]
You already have the option of specifying a specific image id: `node_pool_image_id`

The problem, as you rightly pointed out, is that this will vary by region. We have a fix (see https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/302) but the code has become substantially more complex due to the need to also support ARM shapes as well. It would be great if you can test this fix and let us know how you go. 

We also plan on doing the following:

1. immediate: accept the fix in the PR
2. future: obtain an enhancement to have a 1st class data source for OKE node pool images similar to core images with the ability to filter by a number of parameters

**Comment by hyder** [comment]
Please upvote the need for a ds here: https://github.com/terraform-providers/terraform-provider-oci/issues/1285
