### ISSUE TITLE
data.oci_core_images.oracle_images.images is empty list of object   for oci-oke <=2.3.3

### ISSUE THREAD

**Issue by bieksaz** [oracle-terraform-modules/terraform-oci-oke#290]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.29
terragrunt v0.24.4
provider.oci: version = "~> 4.22"

### Affected Resource(s)

base.operator
data.oci_core_images.oracle_images.images is empty list of object

### Terraform Configuration Files

configurations here have no impact

### Debug Output

no need, because it is clear where the issue lies

### Expected Behavior

should work with older terraform 12.* version (oci-oke version <= v2.3.3)

### Actual Behavior

stopped working, due to OCI seems to have removed oracle linux 7.8 

### Steps to Reproduce

use oci-oke version <=2.3.3 to plan resources that use oracle linux and it will fail.

### Important Factoids

there is an issue now with terraform-oci-oke versions (<=2.3.3) for terraform version 12.* that we are still using. I have tracked down that our version oci-oke v2.3.2 is using oke-base v1.3.3 which then goes to oci-operator 1.0.14  and that one in datasources is taking data from oci_core_images  where it filters BY operating_system_version = "7.8" (HARDCODED) which seems to no longer exist in OCI. So basically anything that was for working for terraform 12.* (it goes up to oci-oke v2.3.3, later versions do not support terraform 12.*) is not longer functioning at all.. :/
can you guys make a fix on oci-operator version 1.0.14 to point to 7.9, or even better, not depend on hardcoded version (just like in latest oci-operator version) ???

**Comment by hyder** [comment]
Hi, sorry for the trouble. We just came to realize this as well and have added the ability to control operator version.

We'll try to cut a patch for this.

In the meantime, since you are still using terraform 0.12 and you want to immediately fix the issue, you can change the minimum version in https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/versions.tf#L7 from
0.13 to 0.12

**Comment by bieksaz** [comment]
Hi @hyder, for me it is no longer an issue, as I downloaded locally both base and operator modules and modified them as needed, so for now it will work. I just opened this ticket so that you could change those older versions of operator so they would not be failing for anyone using TF v12.*  like we are.

**Comment by hyder** [comment]
stale issue
