### ISSUE TITLE
Add support for instance principals

### ISSUE THREAD

**Issue by liafizan** [oracle-terraform-modules/terraform-oci-oke#300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to utilize instance principals instead of credentials for provider but looks like that even though we generate our provider for instance-principals, due to expected credentials, we are unable to use instance-principals

under locals.tf 

```
  oci_base_provider = {
    api_fingerprint      = var.api_fingerprint
    api_private_key_path = var.api_private_key_path
    region               = var.region
    tenancy_id           = var.tenancy_id
    user_id              = var.user_id
  }
```
Would need to be either removed or be generated at run time depending on some option specified

### Potential Terraform Configuration

```hcl
provider "oci" {
  auth = "InstancePrincipal"
  region = var.region
}
```

**Comment by hyder** [comment]
For this, we'll have to stop using the base module and use the individual vcn, bastion and operator modules directly. This will be a major change.

**Comment by hyder** [comment]
Hi, the OCI provider team is working on enhancing the provider options. Once this work is completed, we'll revisit this issue. We'll keep it open until then

**Comment by hyder** [comment]
Hi @liafizan, 

This has been tested on the 4.x branch and it works. 

Please ensure the following:
1) your compute instance is part of dynamic group with the necessary rights 
2) environment variable for instance_principal is set (`export OCI_CLI_AUTH=instance_principal`)
3) If you intend to use the extensions stuff, you need to create a policy that gives the dynamic group the ability to manage dynamic groups.

I'll be closing this issue. If you have any further issue, please reopen it.
