### ISSUE TITLE
An empty image_signing_keys list is required.

### ISSUE THREAD

**Issue by Xachman** [oracle-terraform-modules/terraform-oci-oke#301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 

module "oke" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "3.2.0"
  # insert the 9 required variables here
  cluster_access = "public"
  compartment_id                        =   local.compartment_id
  tenancy_id                            =   local.tenancy_id
  user_id                               =   local.user_id
  api_fingerprint                       =   local.api_fingerprint
  api_private_key_path                  =   local.api_private_key_path
  region                                =   local.region

  ssh_public_key_path                   =   "~/.ssh/id_rsa.pub"


  vcn_name                              =   "name"

  existing_key_id                       =   "..."
  node_pools = {
    np1 = {shape="VM.Standard.E4.Flex",ocpus=1,memory=4,node_pool_size=1}
  }

}
```

### Expected Behavior
When not setting use_signed_images to true image_signing_keys is not required.

### Actual Behavior

you get this error

│ Error: Missing required argument
│ 
│   on main.tf line 1, in module "oke":
│    1: module "oke" {
│ 
│ The argument "image_signing_keys" is required, but no definition was found.

### Steps to Reproduce
Run module without an empty list for image_signing_keys

1. `terraform apply`

### Important Factoids

I am not 100% sure if this is intended or not.  The documentation didn't make it clear to me I needed to provide the empty list.

**Comment by hyder** [comment]
Hi,

Thanks for logging this issue. I see you're using this as a remote module. 

There are 2 uses for KMS integration and they are controlled by 2 different pair of variables:

1. `use_encryption` and `existing_key_id` are used for encryption of etcd at rest
2. `use_signed_images` and `image_signing_keys` are for enforcing the use of signed images only.

Please use the correct pairs. If this is not clear in the documentation, please let us know and we'll fix it.

**Comment by karthicgit** [comment]
@Xachman There is no default value assigned for the variable image_signing_keys thats the reason . we will set the empty list as default value so when you set use_signed_images to false you don't need to pass the image_signing_keys variable.As of now you have to set this value .

**Comment by Xachman** [comment]
@karthicgit thanks!  I got around this by setting the empty list for image_signing_keys.
