### ISSUE TITLE
 Error Message: Invalid nodeShape: Node shape and image are not compatible

### ISSUE THREAD

**Issue by judab5ericom** [oracle-terraform-modules/terraform-oci-oke#303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```hcl

Relevant section:


node_pools = {
  pool1 = {shape="VM.Standard.E2.4",node_pool_size=1,boot_volume_size=100,label={"x"="b"} }
  pool2 = {shape="VM.Standard.E2.4",node_pool_size=3,boot_volume_size=100,label={"x"=""b"}  }
}

#node_pool_image_id = "none"                     #<--------- this ode_pool_image_id stopped working
#                                                                  # so i moved to the one below
node_pool_image_id = "ocid1.image.oc1.uk-london-1.aaaaaaaaznor73ldvqafb3f4iwymzfe4bepjjaygjmbf27xwm2wwlra4tola"


# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Debug Output
https://gist.github.com/judab5ericom/b3c334a9b83a7022efe8e0e79461f472.js

### Expected Behavior

Expect that a new cluster with node pool will be create , however due to Invalid Image issue then the NodePools fails

### Actual Behavior

Fail when creating nodepools

### Steps to Reproduce

take default terraform.tfvars  
make sure you have the minimal details such ociid/key/region/compartment
try bring up Kube Cluster make sure the nodepools will configure as shape = "VM.Standard.E2.4"

1. `terraform apply`

### References
Might relate to issue  400-InvalidParameter for node image #289

**Comment by karthicgit** [comment]
@judab5ericom We have the fix ready.could you please clone the repo https://github.com/karthicgit/terraform-oci-oke.git
and  confirm its working fine for you.

**Comment by judab5ericom** [comment]
it is working,
I successfully built cluster with two node Pools
my tfvars contain  node_pool_image_id = "none"
the node created with this image  Oracle-Linux-7.9-2021.05.12-0

one thing not clear and i will check it later (and I might not relate to this issue )   my script configure to deploy on region X 
while the deployment goes to region Y,    Probably relate to my script I will do additional run tomorrow

**Comment by judab5ericom** [comment]
When trying  to use different shape such Flex then it fail with the same Invalid Shape

**Comment by hyder** [comment]
I think you have 2 issues here. For the region problem, I've replied in the other issue you've opened and you need to initialize your provider. 

When you say Flex is not working, is this against what's currently in the repo or in @karthicgit's PR?
