### ISSUE TITLE
Python script Failure for oci connect from bastion node

### ISSUE THREAD

**Issue by avijit7** [oracle-terraform-modules/terraform-oci-oke#31]
The "is_worker_active" resource is able to login to the bastion successfully after creation but fails 
at the remote_exec step mentioned below:

resource null_resource "is_worker_active" {
  ................
  provisioner "remote-exec" {
    inline = [
      "chmod +x $HOME/is_worker_active.py",
      "while [ ! -f $HOME/node.active ]; do $HOME/is_worker_active.py; sleep 10; done",
    ]
 
  count = "1" 
}

The failure says:
ServiceError:
{
    "code": "NotAuthorizedOrNotFound",
    "message": "Authorization failed or requested resource not found.",
    "opc-request-id": "7989A2AF3D324AE58BB7E991CEC19D8B/34FEA76D72131B65E6833EF2E40764CC/335199A4F1B9BC0F9CD5BE38F7DCEA1E",
    "status": 404
}

Anything needed at the bastion host for this to succeed? kubectl  works fine from the bastion for the 'opc' user.

**Comment by hyder** [comment]
Can you please set enable_instance_principal= true and try?

**Comment by avijit7** [comment]
Thank you. It works after setting enable_instance_principal=true. It works fine now end to end.

**Comment by hyder** [comment]
Please understand the impact of instance_principal before enabling it.
