### ISSUE TITLE
"cannot unmarshal DNS message" in data "oci_waas_edge_subnets" "waf_cidr_blocks"

### ISSUE THREAD

**Issue by willemsendennis** [oracle-terraform-modules/terraform-oci-oke#313]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/oci v4.36.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

I've also tried Terraform v1.0.3; which makes no difference

### Affected Resource(s)

data "oci_waas_edge_subnets" "waf_cidr_blocks"

### Terraform Configuration Files

The only changes I have made compared to the terraform.tfvars.example are the following:
I've shortened some of the variables with ....etc. to hide some potentially sensitive info
```hcl
api_fingerprint = "31:f9:f7:35:0e.....etc."
api_private_key_path = "~/.oci/oci_api_key.pem"
region = "eu-amsterdam-1"
tenancy_id = "ocid1.tenancy.oc1..aaaaaaaalmam3mmw.....etc."
user_id = "ocid1.user.oc1..aaaaaaaaxfta2g5bmjv72y7oz.....etc."
compartment_id = "ocid1.compartment.oc1..aaaaaaaa.....etc."
label_prefix = "nxs-dvza-test"
ssh_private_key_path = ".oci/dummy-ssh"
ssh_public_key_path = ".oci/dummy-ssh.pub"
bastion_enabled = false
operator_enabled = false
cluster_name = "cluster"
node_pools = {
  np1 = {
    shape = "VM.Standard.E3.Flex",
    ocpus = 2,
    node_pool_size = 3
  }
}

node_pools_to_drain = [ "np1" ]
```

### Panic Output

https://gist.github.com/willemsendennis/c1cb7f10cd838bd11ed3ee8c80d0b95e

### Expected Behavior

No waas/waf errors should be thrown, especially since we didn't enable it.

### Actual Behavior

Error: Get "https://waas.eu-amsterdam-1.oci.oraclecloud.com/20181116/edgeSubnets": dial tcp: lookup waas.eu-amsterdam-1.oci.oraclecloud.com on 172.31.96.1:53: cannot unmarshal DNS message

  on modules/okenetwork/datasources.tf line 22, in data "oci_waas_edge_subnets" "waf_cidr_blocks":
  22: data "oci_waas_edge_subnets" "waf_cidr_blocks" {

### Steps to Reproduce

1. clone the git repo
2. apply the changes I have mentioned above for the terraform.tfvars
3. `terraform init` 
4. `terraform plan` 

### Important Factoids

I have tried region eu-amsterdam-1 and eu-frankfurt-1
Last working version I've tried that didn't have this issue is oracle-terraform-modules/oke/oci 3.0.0

**Comment by hyder** [comment]
Hi @willemsendennis,

In the other issue, as a quick suggestion, I mentioned the following:

1. Create a group and add the terraform user to the group
2. Create a policy in root compartment with the following statement: "Allow group to read waas-family in tenancy"
3. And then try again by uncommenting the datasource? Please replace the groupname in (2) as appropriate.

To which you replied:

Unfortunately adding the policy to the group where the terraform user is part of didn't help.

With the same user I am able to perform the following oci cli waas command, e.g.:
oci waas waas-policy list --compartment-id=...

Can I confirm you added the "Allow group to read waas-family in tenancy" and it still didn't work?

**Comment by willemsendennis** [comment]
Hi @hyder,

Yes, I added the `read waas-family in tenancy` to the group the user is part of.
(Also tried `manage waas-family` and even tried creating a separate group with waas policies, just to be sure)
Without success.

**Comment by hyder** [comment]
Hi @willemsendennis, I think we have identified a temporary fix but we are still not sure why this is happening. We'll follow up with our engineering team internally.

**Comment by willemsendennis** [comment]
Great, thank you @hyder for the status update.

**Comment by hyder** [comment]
@willemsendennis , can you please test?

**Comment by willemsendennis** [comment]
Hi @hyder,

Yes I can confirm this works as expected.
Enabling WAF is on our todo list, seeing this fix (although also a correct fix) is sort of a workaround for the issue I do wonder if we will hit the issue again. 
But, until then, thank you for the quick actions!

**Comment by hyder** [comment]
Glad this works for now. Yes, we are aware. This is just to get you going while we figure out why this is happening.
