### ISSUE TITLE
[Feature] Make it possible to enable OCI Bastion plugin on operator host

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#321]
At this moment operator host, the OCA bastion plugin is not enabled, but there has to be a way to enable the plugin via configuration options.

<img width="1424" alt="Screenshot 2021-08-18 at 13 37 08" src="https://user-images.githubusercontent.com/3034091/129884689-a0cf126e-c7d8-46c4-b056-f261771686cc.png">

**Comment by hyder** [comment]
Closed in #332
