### ISSUE TITLE
[Feature] Add missing security rule to allow traffic flow within the LB subnet

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#326]
Configuration:
1. OKE cluster with public OCI LB.
2. OCI API GW deployed into the same public subnet as OCI LB.

But it appears that the traffic is not flowing from a public API GW to public OCI LB via private IP addresses (from the following IP pool: `10.0.2.32/27`).
The reason for that is a missing egress rule on the LB subnet that allows both HTTP/HTTPS traffic on the following destination pool `10.0.2.32/27`.
It makes any incoming HTTP/HTTPS request to OCI API GW timeout because the network is not reachable.

**Comment by hyder** [comment]
Why would you want the LB balancer to be public if you have a public API gateway? Shouldn't you use a private LB instead?

**Comment by denismakogon** [comment]
I thought I explained this: we'd like to use public API GW, therefore a subnet that it is attached to must be public as well.

So, we deploy an Ingress object we receive an OCI LB with a private IP and later on we connect API GW to OCI LB and let them communicate with each other through private IPs, but the only service that has a public IP is an. API GW.

Our setup is: public subnet for LB, but every LB provisioned in that subnet receives a private IP intentionally, we use API GW connected to LB public subnet to work as a reverse proxy to LB.

**Comment by hyder** [comment]
You can achieve this by the following:
1. Set your `lb_subnet_type` to `both` - this will create 2 subnets for lb: public and private
2. Use the public lb subnet to create your api gw
3.  Use the lb annotations to deploy your internal lb to the private subnet: https://github.com/oracle/oci-cloud-controller-manager/blob/master/docs/load-balancer-annotations.md

**Comment by denismakogon** [comment]
I'm sorry, but it doesn't solve the issue described above. It is not related to a type of load balancer, but to the absence of a security rule that prevents traffic flow between components of a system bound to the LB subnet.
I'm still not able to make API GW talk to LB unless I allow ingress traffic from any IP address from the LB subnet.
