### ISSUE TITLE
OCI Bastion --> operator host --> worker nodes

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#330]
At this moment, if SSH access is allowed for worker nodes, we are able to ssh into a worker node from an operator host.

Unfortunately, an ingress rule on a worker subnet is too strict:  only IP addresses from`10.0.0.0/30` are allowed. It means that we cannot SSH into the worker node from an operator host.

**Comment by hyder** [comment]
Duplicate of #327

**Comment by hyder** [comment]
closed in #334
