### ISSUE TITLE
one issue when execute terraform init script

### ISSUE THREAD

**Issue by davinwei2017** [oracle-terraform-modules/terraform-oci-oke#35]
[opc@console-1 oke-terraform]$ terraform init
Initializing modules...
- auth in modules/auth
- base in modules/base
- base.bastion in modules/base/bastion
- base.vcn in modules/base/vcn
- network in modules/okenetwork
- oke in modules/oke
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Missing key/value separator

  on modules/okenetwork/security.tf line 57, in resource "oci_core_security_list" "workers_seclist":
  51:
  52:
  53:
  54:
  55:
  57:       tcp_options {

Expected an equals sign ("=") to mark the beginning of the attribute value.

**Comment by hyder** [comment]
Looks like you're using TF 0.12. This not supported yet.
