### ISSUE TITLE
chore: add a pre-commit hooks config file

### ISSUE THREAD

**Issue by kral2** [oracle-terraform-modules/terraform-oci-oke#353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is a proposition to introduce a pre-commit config to run some checks on the developer station, before committing. The goal is to do some basic tests and formatting on the code, before it hits the repo.

Currently supported checks would be:
- cleaning trailing whitespaces
- making sure `terraform fmt` has been run before committing code
- running `terraform validate` to detect any syntax problem 

This configuration would be used only if the developer have pre-commit installed and configured. We can update to coding convention later to help new comers.

A next step would be to integrate it as a GitHub Action on "Pull request", so we can verify code compliance at server side.

### New or Affected Resource(s)

N/A

### References

https://pre-commit.com/ is a framework for managing and maintaining multi-language pre-commit hooks.

**Comment by hyder** [comment]
Won't include as @Djelibeybi advised. We'll use post-commit checks.
