### ISSUE TITLE
[Feature] Support node metadata

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#362]
As far as I can see TF provider for OCI support node metadata for OKE (https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/containerengine_node_pool_data_source.go#L106).

Would be nice to have it supported by this module.

**Comment by hyder** [comment]
@denismakogon It's landed in branch 4.x-nm. See #386 

We'll keep this issue open until it's merged with main.

**Comment by hyder** [comment]
Added in #484
