### ISSUE TITLE
[Feature] Output a list of compute instance IDs from all node pool

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#366]
I'd like to have a way to get a list of all instances IDs (from all node pools, the order doesn't matter) in order to create a more tight dynamic group that will be used to collect logs via OCI Logging.

At this moment, we create a dynamic group that uses compartment ID as a matching factor, but if a compartment will have more than 1 cluster -  it will start collecting logs from all clusters or even just compute instances spawned in this compartment.

**Comment by kral2** [comment]
Getting all instance IDs is a reasonable request.

But what if you created the dynamic group based on compartment + a defined tag?

Tag applied on the instances by the module obviously.

**Comment by devoncrouse** [comment]
Have a look at [Using Tags to Manage Access](https://docs.oracle.com/en-us/iaas/Content/Tagging/Tasks/managingaccesswithtags.htm) - with [defined tags](https://oracle-terraform-modules.github.io/terraform-oci-oke/guide/identity_tags.html) optionally applied to created resources, you can form a dynamic group matching on them for more granular control. You might also skim [General Variables for All Requests](https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm#General) in case any of these make sense for your case.

The [`output_detail`](https://oracle-terraform-modules.github.io/terraform-oci-oke/inputs_root.html#input_output_detail) input variable in 5.x will also yield outputs that could be transformed into such a list, though I believe the tag-based approach would be simpler.

Please let us know if you're still not able to achieve what you're after - happy to help further.
