### ISSUE TITLE
terraform apply gets timedout with module.policies.null_resource.update_dynamic_group[0]: Still creating... [9m40s elapsed]

### ISSUE THREAD

**Issue by Jayaram059** [oracle-terraform-modules/terraform-oci-oke#377]
When we run terraform apply it takes around 40 mins of time and keep trying with this module and finally ends up with below result

[31m│[0m [0m[1m[31mError: [0m[0m[1mfile provisioner error[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.oke.null_resource.install_kubectl_operator[0],
[31m│[0m [0m  on modules/oke/k8stools.tf line 26, in resource "null_resource" "install_kubectl_operator":
[31m│[0m [0m  26:   provisioner "file" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mtimeout - last error: Error connecting to bastion: dial tcp
[31m│[0m [0m132.145.143.1:22: connect: connection timed out
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mfile provisioner error[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.policies.null_resource.update_dynamic_group[0],
[31m│[0m [0m  on modules/policies/groups.tf line 49, in resource "null_resource" "update_dynamic_group":
[31m│[0m [0m  49:   provisioner "file" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mtimeout - last error: Error connecting to bastion: dial tcp
[31m│[0m [0m132.145.143.1:22: connect: connection timed out
[31m╵[0m[0m
sed][0m[0m

**Comment by hyder** [comment]
Hi, 

2 questions:
1. Which version of the module are you using?
2. Did you enable the bastion and operator hosts?

**Comment by Jayaram059** [comment]
Thank you so much for quick response on this.


    Which version of the module are you using?
    required_version = ">= 0.13"

    Did you enable the bastion and operator hosts?
    Yes

**Comment by Jayaram059** [comment]
![image](https://user-images.githubusercontent.com/66716567/133435196-a0369c50-932d-4efc-8f86-d6f9cef3965f.png)

**Comment by hyder** [comment]
Is there a way I can contact you?

**Comment by Jayaram059** [comment]
HI, I got one clue, 

Sorry for bothering with this ticket, actually issue is this terraform plan and apply running on a cloud vm from where this bastion is not accessible. but locally it works. 

Let me fix that and get back to you if I saw the issue again
