### ISSUE TITLE
[Feature] Make port definitions on internal LB subnet more restrictive

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#390]
For the following subnet:
- internal LB

security list allows traffic to restricted ports
```
Direction: ingress
Protocol: TCP
Ports to close: 11, 17 - 19, 21, 23 - 25, 43, 49, 53, 70 - 74, 79 - 81, 88, 111, 123, 389, 445, 500, 636, 3306, 3389, 5901, 5985 - 5986, 7001, 8000, 8080, 8443, 8888
```

This has to be addressed by introducing more tight security list rules definitions to prevent access to a set of restricted ports.

**Comment by hyder** [comment]
Closed in #399
