### ISSUE TITLE
[BUG] node pool implicitly substitutes zero-sized node pool with a single-worker nodepool

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#400]
For some reason, an OCI OKE module does not allow its consumers to create a zero-sized node pool, at the same time OCI OKE allows us to do so.

If I will specify the following node pool configuration:
```
node_pools = {
  "playground": {
    "shape": "VM.Standard.E3.Flex",
    "ocpus": 8,
    "memory": 64,
    "node_pool_size": 0,
    "boot_volume_size": 150,
    "label": {
      name="playground"
    },
  },
  "services": {
    "shape": "VM.Standard.E3.Flex",
    "ocpus": 6,
    "memory": 24,
    "node_pool_size": 0,
    "boot_volume_size": 75,
    "label": {
      name="services"
    },
  }
}
```

OKE module will replace `0` with `1` and will attempt to create a node pool with a single worker in a node pool.

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/4.x/modules/oke/nodepools.tf#L24
```terraform
    # set quantity to a minimum of 1 to allow small clusters. 
    size = max(1, lookup(each.value, "node_pool_size", 1))
```

**Comment by hyder** [comment]
Closed in #401
