### ISSUE TITLE
oke.network_oci submodule is detecting changes in the default tags for oci_core_security_list(s) and triggering cluster re-creation on fresh cluster.

### ISSUE THREAD

**Issue by jeremyd** [oracle-terraform-modules/terraform-oci-oke#404]
### Bug description and details

OCI appears to be adding default_tags onto the oci_core_security_list(s).  The tags are Oracle-Tags.CreatedBy and CreatedOn.  I do not have any default tags set for this compartment, I do not know if this is possible to turn off.  I'm able to work around this issue by adding default_tags onto the ignore_changes list for these three oci_core_security_list(s) in the oke.network_oci submodule.

### Terraform Version and Provider Version

```
Terraform v1.0.8
terraform_oci_oke version = "v3.3.0"
registry.terraform.io/hashicorp/oci version = "4.45.0"
```

### Affected Resource(s)

oke_network

### Expected Behavior

Terraform should create an empty plan (no changes)

### Actual Behavior

Terraform plan includes an entire cluster replacment.

### Steps to Reproduce

Create a new cluster. (terraform apply)
No changes.
Run terraform apply a 2nd time.

###  Output 

  # module.oke.module.network.oci_core_security_list.control_plane_seclist will be updated in-place
  ~ resource "oci_core_security_list" "control_plane_seclist" {
      ~ defined_tags   = {
          - "Oracle-Tags.CreatedBy" = "jeremy" -> null
          - "Oracle-Tags.CreatedOn" = "2021-10-05T20:26:51.451Z" -> null
        }
        id             = "ocid1.securitylist.oc1.phx.xyz"
        # (6 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }

  # module.oke.module.network.oci_core_security_list.pub_lb_seclist[0] will be updated in-place
  ~ resource "oci_core_security_list" "pub_lb_seclist" {
      ~ defined_tags   = {
          - "Oracle-Tags.CreatedBy" = "jeremy" -> null
          - "Oracle-Tags.CreatedOn" = "2021-10-05T20:26:51.344Z" -> null
        }
        id             = "ocid1.securitylist.oc1.phx.xyz"
        # (6 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # module.oke.module.network.oci_core_security_list.workers_seclist will be updated in-place
  ~ resource "oci_core_security_list" "workers_seclist" {
      ~ defined_tags   = {
          - "Oracle-Tags.CreatedBy" = "jeremy" -> null
          - "Oracle-Tags.CreatedOn" = "2021-10-05T20:26:51.730Z" -> null
        }
        id             = "ocid1.securitylist.oc1.phx.xyz"
        # (6 unchanged attributes hidden)

        # (9 unchanged blocks hidden)
    }
```


### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

<!--- Thank you for keeping this note for the community --->

**Comment by hyder** [comment]
Closed in #405
