### ISSUE TITLE
When setting up a separate OCI bastion service I am unable to connect to the private cluster due to missing egress rule.

### ISSUE THREAD

**Issue by jeremyd** [oracle-terraform-modules/terraform-oci-oke#406]
### Bug description and details

The control plane subnet security_list does not allow EGRESS within the subnet (which is where the bastion service is).  This blocks access to the bastion service.  I have cluster_access_source set to the entire VCN but this only sets the ingress rule and not the egress.  When I set the egress rule I am able to connect to the kubernetes API via the bastion service session.

### Terraform Version and Provider Version

```
Terraform v1.0.8
terraform_oci_oke version = "v3.3.0"
registry.terraform.io/hashicorp/oci version = "4.45.0"
```

### Affected Resource(s)

oke_network

### Expected Behavior

I'm using the new bastion service and provisioning it outside this module (since v3.3.0 does not have this feature yet).  I create the bastion service using the module https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/bastion_bastion

Bastion service should be able to connect to the control plane subnet and allow access.  ( See: https://www.ateam-oracle.com/post/using-oci-bastion-service-to-manage-private-oke-kubernetes-clusters )

### Actual Behavior

Bastion times out the client connecting to the kubernetes API.

### Steps to Reproduce

Create a new cluster.  Create a bastion service that connects to the control plane subnet.  Attempt to connect to kubernetes following the above guide.

**Comment by jeremyd** [comment]
Another workaround is connecting the bastion service to the workers subnet.  This doesn't require a code change.  Is this a better solution?

**Comment by karthicgit** [comment]
@jeremyd  bastion service feature is available in 4.x release . Is it ok to use that ?

**Comment by jeremyd** [comment]
Fix is merged, verified it works for me.

**Comment by hyder** [comment]
hi @jeremyd,

Happy New Year. Just checking, what's the status on this? Is this still a problem?
