### ISSUE TITLE
File provisioner doesn't like ~ in path

### ISSUE THREAD

**Issue by agregory999** [oracle-terraform-modules/terraform-oci-oke#447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

all script templates that write to operator via file provisioner 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Debug Output

```
Connecting to remote host via SSH...
    Host: 10.0.0.13
    User: opc
    Password: false
    Private key: true
    Certificate: false
    SSH Agent: false
    Checking Host Key: false
    Target Platform: unix
  Using configured bastion host...
    Host: 150.136.209.71
    User: opc
    Password: false
    Private key: true
    Certificate: false
    SSH Agent: false
    Checking Host Key: false
  Connected!
  chmod: cannot access '/home/opc/install_kubectl.sh': No such file or directory
  /tmp/terraform_1380187209.sh: line 3: /home/opc/install_kubectl.sh: No such file or directory
```

### Expected Behavior

Scripts should be written to operator home (/home/opc) so they can be executed.

### Actual Behavior

Files (scripts) are not written on the operator.  Thus the configuration is incomplete.

### Steps to Reproduce

If using a later version of terraform it appears to not write the files from the provisioners that use ~ in the destination path.

### Important Factoids

Seems to only happen with the latest versions of terraform

### References

https://www.terraform.io/language/resources/provisioners/file

**Comment by karthicgit** [comment]
@agregory999 Thanks for reporting. I will be working on it .
