### ISSUE TITLE
Update mechanism for OCIR regions by using the region variable itself

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-oke#450]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add support for Johannesburg. 

https://docs.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by hyder** [comment]
@karthicgit Just discussed this with @snafuz, he has a slick proposal which will make maintaining this easier. I'm reassigning it to him

**Comment by karthicgit** [comment]
@hyder Thanks for the update.
