### ISSUE TITLE
compile error for 4.1.4 version

### ISSUE THREAD

**Issue by davinwei** [oracle-terraform-modules/terraform-oci-oke#475]
hello. all:
 when i download the latest 4.1.4 version and execute terraform plan, and it throw following exception, any comments
$ terraform plan
╷
│ Error: Invalid value for input variable
│ 
│   on terraform.tfvars line 192:
│  192: freeform_tags = {
│  193:   # vcn, bastion and operator freeform_tags are required
│  194:   # add more freeform_tags in each as desired
│  195:   vcn = {
│  196:     environment = "dev"
│  197:   }
│  198:   bastion = {
│  199:     access      = "public",
│  200:     environment = "dev",
│  201:     role        = "bastion",
│  202:     security    = "high"
│  203:   }
│  204:   operator = {
│  205:     access      = "restricted",
│  206:     environment = "dev",
│  207:     role        = "operator",
│  208:     security    = "high"
│  209:   }
│  210: }
│ 
│ The given value is not valid for variable "freeform_tags": attribute "oke" is required.

**Comment by karthicgit** [comment]
You can add the block below in freeform_tags in terraform.tfvars
oke = {
      service_lb = {
        environment = "dev"
        role        = "load balancer"
      }
    }

**Comment by hyder** [comment]
closed in #477
