### ISSUE TITLE
empty policy statement 

### ISSUE THREAD

**Issue by karthicgit** [oracle-terraform-modules/terraform-oci-oke#476]
In 4.1.4 version a policy was created with empty statements. Running terraform plan gives the error
Error: statements: attribute supports 1 item as a minimum, config has 0 declared
with module.oke.oci_identity_policy.oke_volume_kms,
│   on modules/oke/iam.tf line 38, in resource "oci_identity_policy" "oke_volume_kms":
│   38: resource "oci_identity_policy" "oke_volume_kms" {

**Comment by hyder** [comment]
Closed in #477
