### ISSUE TITLE
Key management update causes failure to run

### ISSUE THREAD

**Issue by atimgraves** [oracle-terraform-modules/terraform-oci-oke#478]
The 11th Feb update introduced a regression, I get the error below.

with module.oke.oci_identity_policy.oke_volume_kms,
│   on modules/oke/iam.tf line 38, in resource “oci_identity_policy” “oke_volume_kms”:
│   38: resource “oci_identity_policy” “oke_volume_kms” {

I suspect this may be because I have one of operator, bastion set to false (they are not needed for the lab I am running)

If I force the use of the previous commit (7th Feb) then it works with the below tfvars (This is a template that is modified in a script, hence WORKER_SHAPE and so on as placeholders)

terraform.tfvars contents
compartment_id="COMPARTMENT_OCID"
tenancy_id="OCI_TENANCY"
home_region="OCI_HOME_REGION"
region="OCI_REGION"
cluster_name="CLUSTER_NAME"

vcn_name="oke-vcn-CLUSTER_NAME"

create_bastion_host=false
create_bastion_service=false
create_operator=false
control_plane_type="public"
control_plane_allowed_cidrs=["0.0.0.0/0"]

label_prefix="oke"

node_pools = {
  pool1 = { shape = "WORKER_SHAPE", ocpus = 1, memory = 16, node_pool_size = 3, boot_volume_size = 50, label = {pool = "pool1" } }
}

**Comment by karthicgit** [comment]
@atimgraves Its been fixed with the recent merge
