### ISSUE TITLE
system_tags forces unnecessary update of cluster

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-oke#480]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
After creating a cluster, if we run terraform apply again, terraform will update the cluster. This update is forced by the `system_tag`

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by fabienpelletier** [comment]
definitely an annoying issue as what should be a 30s simple `terraform apply` ends up taking the close to half an hour.

**Comment by fabienpelletier** [comment]
Thank you @hyder, just upvoted and commented on the issue! I'll experiment with the workaround later on today.

**Comment by hyder** [comment]
I can confirm Terraform OCI provider v4.67 fixes the issue.
