### ISSUE TITLE
How to configure kubelet ?

### ISSUE THREAD

**Issue by icy** [oracle-terraform-modules/terraform-oci-oke#485]
Hi team,

How can we (re)configure kubelet to secure it against memory/cpu hogging problem? Can we use kubelet-config and/or is there any terraform option to do that?

on kubelet config please see https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

Thanks

**Comment by hyder** [comment]
Hi, 

You can use cloud-init to configure kubelet. See here: https://blogs.oracle.com/cloud-infrastructure/post/container-engine-for-kubernetes-custom-worker-node-startup-script-support to see an example. 

Cloud-init support is being added in #484. I've just sent a PR today. It would be great if you can test.

**Comment by icy** [comment]
@hyder , thanks for your useful information. I will let my team know if they can have some tests. I think they are still using some old versions of the module which makes tests kind impossible. I will keep you posted.

**Comment by hyder** [comment]
We just merged cloud init with main. If there are any issues, do let us know.

Closing this for now.

**Comment by icy** [comment]
Released in v4.1.6 https://github.com/oracle-terraform-modules/terraform-oci-oke/releases/tag/v4.1.6
