### ISSUE TITLE
Burstable shapes

### ISSUE THREAD

**Issue by braunsonm** [oracle-terraform-modules/terraform-oci-oke#490]
Hello,

I am looking to use this module to create a node pool using E4 Flex that is burstable. This is [possible](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_instance#baseline_ocpu_utilization) using the instances resource in the OCI TF Provider but doesn't seem to be a supported configuration option in this module.

Thank you!

**Comment by karthicgit** [comment]
@braunsonm I believe we don't have this option available yet in nodepool shape.  https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/containerengine_node_pool

**Comment by braunsonm** [comment]
@karthicgit ah perhaps that was my confusion. Would it make sense to open an issue with the OCI provider team?

**Comment by karthicgit** [comment]
@braunsonm Before raising a issue i would suggest to check whether this feature is available in OKE.
