### ISSUE TITLE
Node pools being recreated when there are no changes to configuration

### ISSUE THREAD

**Issue by codex70** [oracle-terraform-modules/terraform-oci-oke#495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
registry.terraform.io/hashicorp/oci
version     = "4.67.0"
```

### Expected Behavior

When running an apply with minimum configuration and a copy of sample tfvars file, the fist apply of Terraform should create the required infrastructure. If there are no changes to the configuration, the second apply should not need to modify the deployed infrastructure.
### Actual Behavior

When running apply for the second time, it modifies the node pools leading to a long delay in applying the changes
### Steps to Reproduce

1. `terraform apply`

**Comment by hyder** [comment]
Hi, 
Can you please try with oci provider 4.68? I tested it with v4.68 and it didn't happen

**Comment by codex70** [comment]
Hi @hyder, this doesn't make any difference. I have updated to v4.68 and done a completely clean install. When running Terraform for a second time I still get the following plan:
```
# module.oke.module.bastion[0].oci_core_instance.bastion has changed
  ~ resource "oci_core_instance" "bastion" {
      + extended_metadata   = {}
        id                  = "ocid1.instance...u7pa"
        # (17 unchanged attributes hidden)

      ~ create_vnic_details {
          + nsg_ids                   = []
            # (9 unchanged attributes hidden)
        }

        # (7 unchanged blocks hidden)
    }

  # module.oke.module.operator[0].oci_core_instance.operator has changed
  ~ resource "oci_core_instance" "operator" {
      + extended_metadata                   = {}
        id                                  = "ocid1.instance.oc1....4sa"
        # (18 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }
Plan: 4 to add, 3 to change, 4 to destroy.
```
I'm also left with the issue of NSGs if the services are not setup with service type load balancer which adds to the load balancer.

**Comment by hyder** [comment]
No worries @codex70. Thanks for letting us know. I'm closing this issue.
