### ISSUE TITLE
WARNING: this provider has moved to oracle/oci. Please update your source in required_providers.

### ISSUE THREAD

**Issue by mailbox171** [oracle-terraform-modules/terraform-oci-oke#499]
Hello, I am using version 4.1.6.

Terraform init gives this warning, don't know how to fix it. It is due to the OKE module?

 Warning: Additional provider information from registry
â”‚ 
â”‚ The remote registry returned warnings for registry.terraform.io/hashicorp/oci:
â”‚ - For users on Terraform 0.13 or greater, this provider has moved to oracle/oci. Please update your source in required_providers.
â•µ

My versions are the following.

Initializing modules...
Downloading registry.terraform.io/oracle-terraform-modules/oke/oci 4.1.6 for oke...
- oke in .terraform/modules/oke
Downloading registry.terraform.io/oracle-terraform-modules/bastion/oci 3.0.0 for oke.bastion...
- oke.bastion in .terraform/modules/oke.bastion
- oke.bastionsvc in .terraform/modules/oke/modules/bastionsvc
- oke.extensions in .terraform/modules/oke/modules/extensions
- oke.network in .terraform/modules/oke/modules/network
- oke.oke in .terraform/modules/oke/modules/oke
Downloading registry.terraform.io/oracle-terraform-modules/operator/oci 3.0.3 for oke.operator...
- oke.operator in .terraform/modules/oke.operator
Downloading registry.terraform.io/oracle-terraform-modules/vcn/oci 3.0.0 for oke.vcn...
- oke.vcn in .terraform/modules/oke.vcn

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/cloudinit from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/time from the dependency lock file
- Reusing previous version of hashicorp/local from the dependency lock file
- Reusing previous version of hashicorp/oci from the dependency lock file
- Using previously-installed hashicorp/local v2.2.2
- Using previously-installed hashicorp/oci v4.68.0
- Using previously-installed hashicorp/cloudinit v2.2.0
- Using previously-installed hashicorp/null v3.1.1
- Using previously-installed hashicorp/time v0.7.2

Thank you very much.

**Comment by kral2** [comment]
Hello,

oci provider has recently moved from an HashiCorp owned repo to an [Oracle owned repo](https://registry.terraform.io/providers/oracle/oci/latest). The warning reflects this change.

You need to reflect this change in the code calling the module.

In your `terraform` block, the source argument now needs to be similar to this:

```
terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
    }
  }
}
```

**Comment by kral2** [comment]
> Yes, I think we need to update the required_providers. 

> Yes, I think we need to update the required_providers. 

Beware when making this change, the new repo hosting the provider have only the last two versions published. Changing from `hashicorp/oci` to `oracle/oci` may need to be done together with a version constraint.

`version >= "4.67.3"`

**Comment by hyder** [comment]
Also, I wonder if the existing resources created by `hashicorp/oci` will get deleted and then recreated on the next terraform apply.

**Comment by mailbox171** [comment]
That would be dangerous..

maybe having a property like "oci_provider_source" (default="hashicorp/oci") would help to make user decide if/when do the switch

**Comment by hyder** [comment]
ok, I just tested with the VCN module standalone. The good news is that no resources were changed/destroyed and recreated after switching the provider to `oracle/oci`.

However, as the oke module also relies on vcn, bastion and operator, we'll need to update and cut a new release for each as well.

**Comment by hyder** [comment]
Dependent on https://github.com/oracle-terraform-modules/terraform-oci-vcn/issues/85

**Comment by kral2** [comment]
> That would be dangerous..
> 
> 
> 
> maybe having a property like "oci_provider_source" (default="hashicorp/oci") would help to make user decide if/when do the switch

I think the terraform block do not allow variables or interpolation syntax.
