### ISSUE TITLE
bug: invalid index error when using oke module with the bare minimum required input as per documentation

### ISSUE THREAD

**Issue by luckeyca** [oracle-terraform-modules/terraform-oci-oke#512]
When only using the bare minimum required input values as per documentation, the module doesn't work. 

====
code
====

```
module "oke" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "4.2.1"

  providers = {
    oci.home = oci.home
  }

  compartment_id = var.compartment_id
  home_region    = var.region
  region         = var.region
  tenancy_id     = var.tenancy_id

  # vcn_cidrs = var.vcn_cidrs

  # cluster_name       = var.oke_name
  # kubernetes_version = var.kubernetes_version

  # services_cidr = var.services_cidr

  # node_pool_os_version = var.node_pool_os_version

  # node_pools = var.node_pools
}
````

Expected result: vcn and subnets will be created using the default values, along with the oke cluster.
Actual result: error message below:

 Error: Invalid index
│ 
│   on .terraform/modules/oke/modules/network/locals.tf line 23, in locals:
│   23:   fss_subnet = cidrsubnet(local.vcn_cidr, lookup(var.subnets["fss"], "newbits"), lookup(var.subnets["fss"], "netnum"))
│     ├────────────────
│     │ var.subnets is map of object with 6 elements
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/oke/modules/network/locals.tf line 23, in locals:
│   23:   fss_subnet = cidrsubnet(local.vcn_cidr, lookup(var.subnets["fss"], "newbits"), lookup(var.subnets["fss"], "netnum"))
│     ├────────────────
│     │ var.subnets is map of object with 6 elements
│ 
│ The given key does not identify an element in this collection value.

**Comment by hyder** [comment]
Hi @luckeyca,

Thanks for logging this issue. I can see the problem. When we added the fss module, we didn't add the fss k-v pair for subnets in the variable default. 

Can you please override it like this in your module:

```
  subnets = {
    bastion  = { netnum = 0, newbits = 13 }
    operator = { netnum = 1, newbits = 13 }
    cp       = { netnum = 2, newbits = 13 }
    int_lb   = { netnum = 16, newbits = 11 }
    pub_lb   = { netnum = 17, newbits = 11 }
    workers  = { netnum = 1, newbits = 2 }
    fss      = { netnum = 18, newbits = 11 }
  }
```

**Comment by hyder** [comment]
@karthicgit ^^

**Comment by luckeyca** [comment]
Hi @hyder , the change works. could you please update the official code line so that we don't have to maintain custom module with potential conflict with the official releases down the road? Thanks

**Comment by hyder** [comment]
Yes, I've already marked it as a bug
