### ISSUE TITLE
Allow specifying the ADs each node pool is placed in

### ISSUE THREAD

**Issue by 12345ieee** [oracle-terraform-modules/terraform-oci-oke#515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It's currently not possible to choose which ADs a nodepool is placed in.
All the ADs are enabled, via the code:
```hcl
    dynamic "placement_configs" {
      iterator = ad_iterator
      for_each = local.ad_names
      content {
        availability_domain = ad_iterator.value
        subnet_id           = var.cluster_subnets["workers"]
      }
    }
```

### New or Affected Resource(s)

```
oci_containerengine_node_pool
```

### Potential Terraform Configuration

I propose adding a new parameter to the `node_pools` submap to specify the AD list.
An empty parameter would mean every AD, as it's now to not break existing configurations:

```hcl
  node_pools = {
    pool1_name = { shape = "shape", ocpus = 2, memory = 32, node_pool_size = 1, label = { mylabel = "myvalue" }, 
                  placement_ADs = [AD1] }, # pool only on AD1
    pool2_name = { shape = "shape", ocpus = 2, memory = 32, node_pool_size = 1, label = { mylabel = "myvalue" }, 
                  placement_ADs = [AD1, AD2] }, # pool on AD1,2
    pool3_name = { shape = "shape", ocpus = 2, memory = 32, node_pool_size = 1, label = { mylabel = "myvalue" } },
                   # pool on all ADs
  }
```

the placement code would then become something like:
```hcl
    dynamic "placement_configs" {
      iterator = ad_iterator
      for_each = lookup(each.value, "placement_ADs", "") != "" ? set(lookup(each.value, "placement_ADs", "")) : local.ad_names
      content {
        availability_domain = ad_iterator.value
        subnet_id           = var.cluster_subnets["workers"]
      }
    }
```

**Comment by hyder** [comment]
Hi @12345ieee,

This looks good to me. Would you be willing to send us a PR? 

Just out of curiosity, can you please elaborate on your use case?

**Comment by 12345ieee** [comment]
> This looks good to me. Would you be willing to send us a PR?
Yeah, most likely, just let me get to grips with a development setup.

> Just out of curiosity, can you please elaborate on your use case?
Sure, maybe you guys can suggest me a better workflow.

In a 3AD cluster not everything is triple-redundant, I need to deploy some pods with a single replica.
These pods have pvc's, either specified in a PVC resource or created by a StatefulSet template.

By placing these pods in a 3AD nodepool, once the PVCs are created they are effectively bound to a random AD. I know I can do the backup trick to move them and then manually specify the ocid in the pvc manifest, but that's not fun.
The pods can instead change AD freely, because I don't want to manually specify the AD of every pod and I may not even be able to in some helm releases.

So what ended up happening often was that:
* app deployed, pod1 and its pvc are created in AD1
* app redeployed, tons of pods are terminated and rebuilt
* other pods fill the RAM/CPU node space on AD1
* pod1 can't be scheduled, it has no RAM/CPU on AD1 machines, it has an unbound pvc on AD2/3 machines

To fix all this, I want to create a pool that deploys in a single AD, where I deploy these "singleton stateful" pods.

**Comment by hyder** [comment]
Thanks for the explanation. We'll wait for your PR.
