### ISSUE TITLE
Changing bastion_image_id = “Autonomous” to a custom image in terraform.tfvars will lead to fail

### ISSUE THREAD

**Issue by Jayaram059** [oracle-terraform-modules/terraform-oci-oke#516]
HI Team, 

we are trying to provide custom Image for our Bastion setup using terraform provider, somehow its not accepting and throwing below error
bastion_image_id = “Autonomous” If we pass value as this it works if we pass value as bastion_image_id = “ocid1.image.oc1.phx.aaaaaaaa5r6sx3z4daczcrim7pxqtlq4houepmzn3ioqqlflfhe6qbuflajq” fails

Error: Invalid index
│ 
│   on .terraform/modules/base.bastion/datasources.tf line 68, in data "template_cloudinit_config" "bastion":
│   68:     content      = data.template_file.autonomous_cloud_init_file[0].rendered
│     ├────────────────
│     │ data.template_file.autonomous_cloud_init_file is empty tuple
│ 
│ The given key does not identify an element in this collection value: the
│ collection has no elements.

**Comment by hyder** [comment]
Hi,

Thanks for logging this issue. 1 question, when you use a custom image, are there any commands/scripts you would like to be run by cloud-init?

**Comment by Jayaram059** [comment]
Thank you for the quick response, when we use custom image no other commands / scripts need to be run at this moment.
