### ISSUE TITLE
Specify a subnet on a node pool basis

### ISSUE THREAD

**Issue by atimgraves** [oracle-terraform-modules/terraform-oci-oke#522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Have the ability to specify the subnet to be used on a per node pool basis.
Requirement is for pods running in one node pool to have separate routing controls from other node pools (this routing will connect to on-prem environments) there is also a need for controlled communication between node pools.

Scenario. A SP is providing a service, they have a multi tennant application and also specific processing microservcies for each of their end customers. The core multi tennant application sends messages to the per end customer microservices which do end customer specific operations and ultimately connect to back end systems for each of the different end customers using fast connect / vpn (these back end services are unique, and also run in the end customers network.)
We need to ensure that the security separation between the various end customers is maintained, so the plan is so use subnets for end customer specific node pools with routing tables that will only allow traffic to / from the end customers environments. 

### New or Affected Resource(s)

Node pools, networking

**Comment by devoncrouse** [comment]
[Implemented in 5.x](https://oracle-terraform-modules.github.io/terraform-oci-oke/guide/workers_network.html#subnets) - reach out with any questions/feedback, thanks!
