### ISSUE TITLE
Use other network plugin except flannel

### ISSUE THREAD

**Issue by iocn-2-3-4** [oracle-terraform-modules/terraform-oci-oke#527]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to add option for replacing flannel as default network plugin?
currently there is only option for adding calico alongside flannel
but we observe some issues with ip assignment to pods 
seems pods like coredns has been assigned ip by flannel and all new pods assigned ip by calico, and looks like there is little overlapping with ip pools

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by hyder** [comment]
Hi,

It is not possible to change the CNI for now. However, you can use Calico for network policy.

**Comment by iocn-2-3-4** [comment]
Thanks for reply,@hyder !
One more question
If we install calico alongside flannel , we observe some strange behaviour
After cluster installation, in kube-system namespace some pods, like coredns, dns-autoscaler, calico-node-controller are using ip from subnet 10.244.0.0/16
for example:
 coredns-5f5f66466b-tbwxq  10.244.1.2
or
coredns-5f5f66466b-n267r 10.244.0.3
but when we install some other apps, somehow new pods assigned same ip that already has been assigned to existing pods in kube-system, and this kube-system pods starts crashing, because they can't pass readiness health checks
```
 scheduler-app             10.244.0.3   3/3 Running
coredns-5f5f66466b-n267r   10.244.0.3   0/1 Running 
```
and it happens for all ip that already assigned to some system pods, they are reassigned to new pods
when we delete these system pods they recreated and has been assigned new ip and this overlapping never happens again
is it correct behaviour?
