### ISSUE TITLE
Issue enabling waf

### ISSUE THREAD

**Issue by futureecomavi** [oracle-terraform-modules/terraform-oci-oke#540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/oracle/oci v4.83.0
### Affected Resource(s)

When setting enable_waf to true, terraform plan/apply throws the following error:

```╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/oke/modules/network/nsgs.tf line 484, in resource "oci_core_network_security_group_security_rule" "waf_ingress":
│  484:   for_each                  = var.enable_waf == true ? toset(local.waf_cidr_list) : toset([])
│     ├────────────────
│     │ local.waf_cidr_list will be known only after apply
│     │ var.enable_waf is true
│ 
│ The "for_each" set includes values derived from resource attributes that cannot be determined until apply, and so Terraform cannot
│ determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to use a map value where the keys are defined statically in your
│ configuration and where only the values contain apply-time results.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and
│ then apply a second time to fully converge.```

**Comment by hyder** [comment]
Hi, sorry for the delay. 

For now, the way to use this is to do it in 2 phases:

1. Create the cluster `waf_enabled = false`
2. Then run terraform apply again with `waf_enabled = true`

I realise this is not ideal so we'll be reworking this feature, possibly in a different module
