### ISSUE TITLE
Public load balancer  communication not working when using NLB

### ISSUE THREAD

**Issue by elconas** [oracle-terraform-modules/terraform-oci-oke#582]
When deploying a cluster using this module and then deploying public NLB within the cluster, the communication does not work, as the worker nodePort range is only accepting traffic from the CIDR of the lb public subnet, However as the NLB preserves the client IP (L4 load balancer) per default, this needs to be "open to the world" as the NSG would otherwise not match. 

To make this a secure thing, using NSG ID as a source and destination fixes the issue and makes sure only load balancers can access the nodePort range.

Fix:
Grant nodePort range from public / internal lb NSG to worker nodes via NSG linking.

Somehow this would be fixed if https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/425 is implemented.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

$ terraform -v
Terraform v1.2.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.8.0
+ provider registry.terraform.io/oracle/oci v4.94.0

**Comment by elconas** [comment]
Just an update, the module works with working LB when annotating the service type=Loadbalancer with 
```
oci-network-load-balancer.oraclecloud.com/is-preserve-source: false
```
Without this annotation, the communication does not work, as the source IP for the packets is actually "the internet" (as it preserves the client IP on the IP layer)

**Comment by hyder** [comment]
Hi @elconas,

This is controlled by the OKE's CCM. It's not something we can control in this module as we are not deploying a service of type LoadBalancer. 

Thanks for submitting the solution though. It would be great if you can add this to the docs via a PR.

**Comment by elconas** [comment]
Hello @hyder, actually this could be fixed in code, as the firewalling can be based on SecurityrGroup based on other SecurityGroups (I think people call this NSG Linking)  not CIDR's. Adding a SG to SG ingress rume in the worker nodes SG from the lb NSG's fixes this issue actually.

Generally NSG and not CIDR based firewalling would fix it too.

**Comment by hyder** [comment]
Thanks @elconas . Would you be able to send us a PR?

**Comment by hyder** [comment]
Hi @elconas,

Are you able to send us a PR?

**Comment by devoncrouse** [comment]
NSG rules in 5.x are implemented with references to other NSGs for traffic between components as suggested by @elconas - please let us know any issues remain for your use-case. Thanks for the feedback!
