### ISSUE TITLE
Hardcoded cluster_pod_network_options forces oci_containerengine_cluster replacement breaking backwards compatibility

### ISSUE THREAD

**Issue by aibarbetta** [oracle-terraform-modules/terraform-oci-oke#591]
[cluster_pod_network_options field in oci_containerengine_cluster was introduced as optional in OCI provider v4.84.0](https://github.com/oracle/terraform-provider-oci/commit/b7369004fa67083d0dea0a4a3619560fcbc11d26). [OKE hardcodes the oci_containerengine_cluster field since OKE v4.2.6](https://github.com/oracle-terraform-modules/terraform-oci-oke/commit/5f3e3d12229ced0698f9dce131edd9f8689413ef). Clusters created with OKE versions earlier than v4.2.6 that upgrade OKE to version v4.2.6 or later will force recreation of oci_containerengine_cluster because of this change. I believe [cluster_pod_network_options](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/269d3fdd896309157e667558bb885f0c54a3e11d/modules/oke/cluster.tf#L19) should only be added if cni_type is OCI_VCN_IP_NATIVE, and omitted otherwise.

Please let me know if there is any OKE migration instructions I'm missing

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v1.2.8
OKE v3.3.0 to v4.2.6

### Affected Resource(s)
oci_containerengine_cluster

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior
After testing the terraform apply with the optional cluster_pod_network_options setting deleted, the addition of the field no longer forces replacement of the oci_containerengine_cluster
```
      + cluster_pod_network_options {
          + cni_type = (known after apply)
        }
```

### Actual Behavior
Running terraform apply with OKE v4.2.6 in a cluster created with OKE v3.3.0 forces oci_containerengine_cluster replacement breaking backwards compatibility
```
  # module.kubernetes.module.oke.module.oke.oci_containerengine_cluster.k8s_cluster must be replaced
-/+ resource "oci_containerengine_cluster" "k8s_cluster" {
      (...)

      + cluster_pod_network_options { # forces replacement
          + cni_type = "FLANNEL_OVERLAY" # forces replacement
        }

```

### Steps to Reproduce

1. `terraform apply`

**Comment by 12345ieee** [comment]
I had raised the same issue here: https://github.com/oracle-terraform-modules/terraform-oci-oke/discussions/571
This is important for us as well.

**Comment by devoncrouse** [comment]
:eyes:

**Comment by 12345ieee** [comment]
To be honest it's not really an issue of the module itself, old clusters with no set `cni_type` do use flannel behind the scenes, it's just that the backend OCI API (and hence the provider) treat absent `cni_type` and explicit `cni_type=flannel` clusters differently in metadata.

I don't know if this should actually be raised to the provider or even some higher OCI API source, hnce my question in #571 .

**Comment by truddy0** [comment]
Hi @aibarbetta,
thanks for reporting the issue. May I ask question to clarify the version you used? 

> Clusters created with OKE versions earlier than v4.2.12 that upgrade OKE to versions later than v4.2.12 will force recreation of oci_containerengine_cluster because of this change
_I assume that you created a cluster using v4.2.12(the latest version of the release of terraform-oci-oke) and when you switch to the latest branch of main, the cluster gets recreated._

> Actual Behavior
> 
> Running terraform apply with OKE v4.2.6 in a cluster created with OKE v3.3.0 forces oci_containerengine_cluster replacement breaking backwards compatibility
_However, here, you reported that you created a cluster using v3.3.0 and when you switch to v4.2.6 and the cluster gets recreated._ 

Would you like to clarify which version you created cluster firstly and then which version you switched to causing cluster recreation, please? Thanks.

**Comment by aibarbetta** [comment]
Hi @truddy0, sorry I misread [the commit that introduced `cluster_pod_network_options`](https://github.com/oracle-terraform-modules/terraform-oci-oke/commit/5f3e3d12229ced0698f9dce131edd9f8689413ef), the change was introduced in v4.2.6, not v4.2.12. Description is corrected now. 

> Would you like to clarify which version you created cluster firstly and then which version you switched to causing cluster recreation, please? Thanks.

I created my cluster using OKE v3.3.0, and now I'm attempting to upgrade to OKE v4.2.6. What I tried to say in the description is that the change that I believe forces the recreation was introduced in v4.2.6, so any upgrade from a version earlier to version v4.2.6 or later will have this issue.

**Comment by 12345ieee** [comment]
Sorry to ping everyone, but are there any news on this?
We'll want to upgrade to get the kubeconfig file removal when it's released, but this will block us.

Do we need to bring this upstream? Could we make `cni_type = "NONE"` not emit the `cluster_pod_network_options` block at all to enable a backwards compatibility fix?

**Comment by devoncrouse** [comment]
Hi @12345ieee - are you able to confirm if the ignored lifecycle change added in #605 will resolve this? I'm open to trying your suggestion otherwise.

**Comment by 12345ieee** [comment]
It took me a bit more than I thought, but I confirm it worked.
