### ISSUE TITLE
Avoid writing kubeconfig file

### ISSUE THREAD

**Issue by slok** [oracle-terraform-modules/terraform-oci-oke#601]
Hi! :wave: 

Thanks for this module! it truly makes it easier to set up an OKE cluster :)

I would like to be able to not write the kubeconfig file, but seems that it's not possible to avoid that. Am I missing something?

To give more context. We execute terraform using Terraform cloud, which is executed in ephemeral workers, so the file disappears on every run, instead, we store the content of the kubeconfig in Hasicorp's Vault.

This ends that on every run, terraform creates a new resource, so we are always in a drift.

If it's not possible, would be something that you would be interested in? I could submit a PR if required. In the end, I think that where you store the kubeconfig data is up to the user.

**Comment by slok** [comment]
@hyder I think that if you already thought about removing it, that's an even better approach! Users could always grab that without the need for this feature inside the module (and with this fewer options and code to manage on the module).

For example we are doing this:

```terraform
# OKE cluster creation
module "oke_ksa_dev" {
#...
}

# Obtain provisioned Kubeconfig.
data "oci_containerengine_cluster_kube_config" "kube_config" {
  cluster_id = module.oke_ksa_dev.cluster_id
}

# Store in kubeconfig in vault.
resource "vault_generic_secret" "kube_config" {
  path = "my/cluster/path/kubeconfig"
  data_json = jsonencode({
    "data" : data.oci_containerengine_cluster_kube_config.kube_config.content
  })
}
```

**Comment by 12345ieee** [comment]
I didn't know about `oci_containerengine_cluster_kube_config`, talk about a game changer!

Yeah, this could be used as suggested by @slok to grab the data to feed to the `helm_release` the way we wanted in #594 with no issue.

No need for the module to make that file then, just suggest this n the release notes.

**Comment by hyder** [comment]
Thanks @12345ieee. @slok let's remove it completely then.
