### ISSUE TITLE
OKE nodepool is limited to 32 characters

### ISSUE THREAD

**Issue by christophercorn** [oracle-terraform-modules/terraform-oci-oke#628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

An OKE nodepool is limited to 32 chars. 

var.label_prefix can sometimes consume most of those chars, leaving little room for the remainder of the node pool name as defined in each key name of var.node_pools. 

for a more descriptive nodepool name we should have the ability to drop the var.label_prefix name specifically for the oci_containerengine_node_pool resource. this way, we can maintain the functionality of  var.label_prefix  that is used across this terraform module.

### New or Affected Resource(s)

oci_containerengine_node_pool

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by devoncrouse** [comment]
Resolved by #630.
