### ISSUE TITLE
Metrics server should use helm install

### ISSUE THREAD

**Issue by atimgraves** [oracle-terraform-modules/terraform-oci-oke#631]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The metrics server currently uses a shell sctript to download the YAML configuration. The metrics server team now provide a helm chart based approach which allows for greater flexibility

### New or Affected Resource(s)

Metrics server install module, helm chart at https://github.com/kubernetes-sigs/metrics-server

### References

Mertrics server project and helm chart at at https://github.com/kubernetes-sigs/metrics-server

**Comment by devoncrouse** [comment]
Added to 5.x in https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/640
