### ISSUE TITLE
Attach custom instance policy to worker node pool for OCI Log Explore Monitoring and External Secrets

### ISSUE THREAD

**Issue by safoorsafdar** [oracle-terraform-modules/terraform-oci-oke#641]
Hi, 

After reviewing the available issues and documentation, I was unable to find any information on how to attach an instance policy to a worker node. I also checked information related to the cluster auto scaler but still had no luck finding a solution. 

Is there a way to apply custom instance policies to a worker node during provisioning?

Resources I want to use:
https://github.com/oracle-terraform-modules/terraform-oci-logging
External Secrets, Found the article to setup it but not with instance policy. https://medium.com/oracledevs/using-the-external-secrets-operator-with-oci-kubernetes-and-oci-vault-6865f2e1fe35

Thanks,

**Comment by hyder** [comment]
Hi,
Sorry, we seem to have missed this issue. Do you still need help on this?
