### ISSUE TITLE
var.subnets["bastion"] is required even if create_bastion_host = false

### ISSUE THREAD

**Issue by icy** [oracle-terraform-modules/terraform-oci-oke#650]
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/8883c54278ba56302e0db54fcdd1cc5362af078a/modules/network/locals.tf#L13

**Comment by icy** [comment]
I don't want to create any bastion/operator node, but looked like I have to provide subnet information. This is quite annoying:

```
│ Error: Invalid index
│ 
│   on .terraform/modules/cluster/modules/network/locals.tf line 13, in locals:
│   13:   bastion_subnet = cidrsubnet(local.vcn_cidr, lookup(var.subnets["bastion"], "newbits"), lookup(var.subnets["bastion"], "netnum"))
│     ├────────────────
│     │ var.subnets is map of object with 5 elements
│ 
│ The given key does not identify an element in this collection value.
```

**Comment by hyder** [comment]
Sorry for the delay in getting back to you. That's a fair point. We'll improve that
