### ISSUE TITLE
upgrade enhanced cluster - can i know which paramter can be used to upgrade oke cluster to enhanced to enable addon's(CoreDNS, KubeProxy , NativePodNetworking)

### ISSUE THREAD

**Issue by csraovaradev** [oracle-terraform-modules/terraform-oci-oke#674]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by hyder** [comment]
As in #673, we are waiting for a new release

**Comment by hyder** [comment]
You can now use `cluster_type` to choose between basic or enhanced clusters. See https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/terraform.tfvars.example#L183

Note that we haven't implemented addons yet.
