### ISSUE TITLE
passing a list of subnet id's to OKE module fails.

### ISSUE THREAD

**Issue by shb-mll** [oracle-terraform-modules/terraform-oci-oke#682]
It appears the bug reported in this issue https://github.com/oracle/terraform-provider-oci/issues/1662 is resolved and the attribute 
 pod_nsg_ids accepts only lists.  
 Could you please check and remove the element function in line 55. 
 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/128678535/228894936-122dabff-66f2-4317-9fa0-c01082fc4fa2.png">

 
 I ran into below error when passing a list of subnet id's (string) to variable pod_ngs, the error  indicated the attribute pod_nsg_ids is of type list of strings now. 
 In my scenario I am only using the oke module https://github.com/oracle-terraform-modules/terraform-oci-oke/tree/main/modules/oke 
 
![image](https://user-images.githubusercontent.com/128678535/228895273-a0815a37-37cf-496d-97f7-75e754687ce2.png)

Could you look into this issue please. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

$ terraform -v 
Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/oracle/oci v4.113.0

### Affected Resource(s)

oci_containerengine_node_pool

### Terraform Configuration Files

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/modules/oke/nodepools.tf
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by shb-mll** [comment]
Hi Team  could you look into the above and suggest.

**Comment by hyder** [comment]
The issue is still open in the provider

**Comment by devoncrouse** [comment]
@shb-mll Let me know if you're able to confirm resolution for this - thanks.
