### ISSUE TITLE
Failed to setup using create_operator=false

### ISSUE THREAD

**Issue by fcecagno** [oracle-terraform-modules/terraform-oci-oke#693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform 1.3.8
terraform-oci-oke 4.5.4

### Actual Behavior

cp_ingress nsg fails to create because `source` is empty: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/v4.5.4/modules/network/locals.tf#L148-L155

### Steps to Reproduce

Just create a cluster with `create_operator=false`.

### References

Issue introduced by https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/670.
Works with terraform-oci-oke 4.5.3.

**Comment by 12345ieee** [comment]
I reported it here as well: https://github.com/oracle-terraform-modules/terraform-oci-oke/commit/24b301b58f0bbd3a49f9bfc82bd411ebf550286a#commitcomment-107332692 .

**Comment by hyder** [comment]
Thanks for reporting and sorry for the inconvenience.

We've fixed this in [v4.5.5](https://github.com/oracle-terraform-modules/terraform-oci-oke/releases/tag/v4.5.5).
