### ISSUE TITLE
How to name nodes?

### ISSUE THREAD

**Issue by fcecagno** [oracle-terraform-modules/terraform-oci-oke#705]
On OCI console, nodes have a name such as `oke-c48c9d897741-a0dd49f16b02-f415cc6c0523-0` (being prefix `oke-` and suffix `-\d+` as the node number from 0 to n). However, when I do `kubectl get nodes`, nodes have their internal IP addresses as node name.

I was wondering if there's a way to use proper naming on nodes so dashboards such as https://github.com/dotdc/grafana-dashboards-kubernetes could be used out of the box.

**Comment by hyder** [comment]
OKE worker node display names are automatically named IIRC. 

+ @devoncrouse

**Comment by dotdc** [comment]
Hi there 👋 

To fix the issue, the `node` label from `kube_node_info` should match the `nodename` label from `node_uname_info`.

These metrics are coming from [node_exporter](https://github.com/prometheus/node_exporter)

**Comment by hyder** [comment]
I've filed an enhancement request.

**Comment by hyder** [comment]
I'll close the issue for now
