### ISSUE TITLE
Why are defined_tags under ignore_changes in many resources (but not all)?

### ISSUE THREAD

**Issue by 12345ieee** [oracle-terraform-modules/terraform-oci-oke#713]
Consider:

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/89919f9c589cef281a711faa53902099737e8277/modules/storage/fss.tf#L10

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/89919f9c589cef281a711faa53902099737e8277/modules/storage/fss.tf#L24

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/89919f9c589cef281a711faa53902099737e8277/modules/network/seclist.tf#L57

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/89919f9c589cef281a711faa53902099737e8277/modules/oke/cluster.tf#L79

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/89919f9c589cef281a711faa53902099737e8277/modules/oke/nodepools.tf#L137-L143

there are all resources where changes to defined_tags are ignored, while they are not ignored in all other resources.
In one case even the freeform_tags are ignored, while they are not in all other resources.

This was extremely surprising and took a while to figure why the module would update some of its tags and not others.

Is this intended? Or is it just a relic of when the module didn't handle defined_tags?
I'd gladly make a PR to remove all the tag ignores if it'd be accepted.

**Comment by hyder** [comment]
Except for the nodepool, I think they are all optional so you could use the tags to identify the resources.

For nodepools, they allow you to use defined tags so the user become part of a dynamic group and you can then allow worker nodes from that pool to interact with certain OCI services via instance_principal. Using dynamic groups and instance_principal is more secure as

1. you don't need to put an OCI key into a secret and use it for authentication
2. you can give only the exact permission that is needed for your applications running on those worker nodes to the dynamic group. 

See here for an example of when deploying Thanos to OKE and getting Thanos to ship metrics to OCI Object Storage: https://medium.com/oracledevs/deploy-thanos-receive-with-native-oci-object-storage-on-kubernetes-829326ea0bc6

Note that we also have recently added workload identity (https://blogs.oracle.com/cloud-infrastructure/post/oke-workload-identity-greater-control-access) which is another method that you can include in your workload. For those workloads that you need to deploy and you don't have access over the code, the instance_principal method is thus still available as a more secure method.

As for the other resources where we added ignore, there were also some resources which were unnecessarily causing a refresh when there none. This would cause terraform apply to take much longer than usual.

**Comment by devoncrouse** [comment]
We ignore `defined_tags` in practice because these can be [added automatically](https://docs.oracle.com/en-us/iaas/Content/Tagging/Concepts/understandingautomaticdefaulttags.htm), in which case the plan will always report changes as TF tries to remove them as unexpected.

Resolution of https://github.com/hashicorp/terraform/issues/24188 would be helpful for this as well as pool `size` with Cluster Autoscaler enabled, for e.g.

**Comment by 12345ieee** [comment]
We use tags for cost-tracking, not identity management, so changing them has no infrastructural side effects, but the finance department stops annoying me.

I absolutely set the tags automatically via a ns default in all my namespaces, but was trying to rescue a situation where the tag hierarchy changed and I had dozens of clusters to retag correctly.
Adding the default tags fixes future resources, but current ones need to be retagged.

Ended up just removing the ignores from the module, running an apply, putting the module back.
This can be closed, thanks guys.
