### ISSUE TITLE
Use the terraform moved feature when refactoring future module versions.

### ISSUE THREAD

**Issue by cwiggs** [oracle-terraform-modules/terraform-oci-oke#733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When upgrading from 5.0.0-beta.2 to 5.0.0-beta.3 I noticed a lot of resources moved.  In the future it would be nice to use the [moved](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring#moved-block-syntax) feature in terrraform.  

### New or Affected Resource(s)

See the terraform config for some of the affected resources.

### Potential Terraform Configuration

Here an example of some of the resources that I was able to move.

```hcl
moved {
  from = module.oke.module.network.oci_core_subnet.workers
  to   = module.oke.module.network.oci_core_subnet.oke["workers"]
}

moved {
  from = module.oke.module.oke.oci_containerengine_node_pool.nodepools["np1"]
  to   = module.oke.module.workers[0].oci_containerengine_node_pool.workers["np1"]
}

moved {
  from = module.oke.module.oke.oci_containerengine_node_pool.nodepools["np2"]
  to   = module.oke.module.workers[0].oci_containerengine_node_pool.workers["np2"]
}

moved {
  from = module.oke.module.oke.oci_containerengine_cluster.k8s_cluster
  to   = module.oke.module.cluster[0].oci_containerengine_cluster.k8s_cluster
}

moved {
  from = module.oke.module.network.oci_core_subnet.cp
  to   = module.oke.module.network.oci_core_subnet.oke["cp"]
}

moved {
  from = module.oke.module.bastion[0].oci_core_subnet.bastion
  to   = module.oke.module.network.oci_core_subnet.oke["bastion"]
}

moved {
  from = module.oke.module.operator[0].oci_core_subnet.operator
  to   = module.oke.module.network.oci_core_subnet.oke["operator"]
}

moved {
  from = module.oke.module.network.oci_core_subnet.pub_lb[0]
  to   = module.oke.module.network.oci_core_subnet.oke["pub_lb"]
}
```

**Comment by 12345ieee** [comment]
If you're testing 5.x take a look at https://github.com/oracle-terraform-modules/terraform-oci-oke/discussions/718 .
I did a full test as well and reported this exact issue, among others.

**Comment by devoncrouse** [comment]
I agree - adding these `moved` blocks before 5.x is released will help support migration of existing clusters from 4.x like you've noted, and we do intend to document/validate this further ahead of time. There was an expectation of breaking changes initially with these beta releases, though I wouldn't expect module paths to be changing now - let's add them.

**Comment by devoncrouse** [comment]
The `moved` blocks here have been added, and we'll be continuing to review the migration path from 4.x. We'll also be continuing to support the previous versions; no pressure to upgrade.

I'm going to close this issue for now, but please do open others if you see more opportunities to make this easier.
