### ISSUE TITLE
5.x: Implement worker pool `drain` by label

### ISSUE THREAD

**Issue by devoncrouse** [oracle-terraform-modules/terraform-oci-oke#751]
```javascript
worker_pools = {
  pool0 = { create = true, drain = true }
}
```

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/docs/src/guide/workers_drain.md
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/modules/workers/locals.tf#L21
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/modules/utilities/drain.tf

**Comment by thpham** [comment]
Hello, could we imagine having this feature one day as a managed option that is automated by the control plane (and behind the scene an operator on it) ?

An idea would be for example some node labels/annotations on them that trigger it ? I see this as a potential extension of the rolling update mechanism of node pools (when the control plane is updated to a new version of kubernetes and then we want to automatically rollout k8s upgrade to nodes in a pool in sequence. This will first increase the pool +1, wait readiness, annotate the first old member with something that trigger the drain, once everything evicted, destroy the node, and repeat)... very roughly ...

What's your opinion ?

**Comment by devoncrouse** [comment]
Hi @thpham - this is supported on managed pools today with [Cordon/Drain](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengdeletingworkernodes.htm) configuration and [Node Pool Cycling](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengupgradingk8sworkernode_topic-Performing_an_InPlace_Worker_Node_Upgrade_by_Cycling_an_Existing_Node_Pool.htm); the option added here was a small convenience to drain pools through the operator for either managed or self-managed uniformly, but is fairly basic to your point. The option existed in version 4.x of the module so was kept for parity.
