### ISSUE TITLE
5.x What is the proper way to specify node pools, and node labels?

### ISSUE THREAD

**Issue by rodrigc** [oracle-terraform-modules/terraform-oci-oke#770]
My team is using:

```
  source  = "oracle-terraform-modules/oke/oci"
  version = "5.0.0-beta.3"
```

We encountered some problems when trying to set up node pools and apply
labels to each node.

```
environment = "production"
node_pools = {
  blue = {
    shape            = "VM.Standard.E4.Flex",
    ocpus            = 8,
    memory           = 32,
    size             = 5,
    boot_volume_size = 150,
  }
  a = {
    shape            = "VM.Standard.E4.Flex",
    ocpus            = 2,
    memory           = 12,
    size             = 3,
    boot_volume_size = 150,
    node_labels = {
      "node/type" = "a"
    }
  }
  b = {
    shape            = "VM.Standard.E4.Flex",
    ocpus            = 4,
    memory           = 32,
    size             = 6,
    boot_volume_size = 150,
    node_labels = {
      "node/type" = "b"
    }
  }
  c = {
    shape            = "VM.Standard.E4.Flex",
    ocpus            = 4,
    memory           = 24,
    size             = 3,
    boot_volume_size = 150,
    node_labels = {
      "node/type" = "c"
    }
  }
  d = {
    shape            = "VM.Standard.E4.Flex",
    ocpus            = 4,
    memory           = 24,
    size             = 2,
    boot_volume_size = 150,
    node_labels = {
      "node/type" = "d"
    }
  }
}
```

I  found that after a terraform apply,
the `node/type` node label was not applied to the nodes.

What is the correct way to create a node pool and apply node labels?

I have been following the 5.x branch, but got a bit lost, since there have been lots of changes
in the variables with respect to node pools and node labels, and couldn't follow what was going on.

@devoncrouse @hyder @Djelibeybi Any recommendations?

Thanks

**Comment by rodrigc** [comment]
The documentation for node pools has really changed from earlier versions:
https://oracle-terraform-modules.github.io/terraform-oci-oke/guide/workers_mode_nodepool.html

`worker_pools` is documented.
Can I change my TF to from `node_pools` to `worker_pools`?

Can I easily migrate the TF state?

**Comment by devoncrouse** [comment]
@rodrigc The new major version is indeed signifying a number of breaking changes here, as we've restructured the module to better support a number of features being asked for and overall maintainability of the project. Inputs variables have changed to better reflect their purpose/clean up usage. This is still in development along with associated documentation, and the `5.0.0-beta.3` version published to the registry doesn't include the latest fixes in the branch (we'll be publishing a new revision soon).

If you'd like to evaluate with the latest, you can [point to the branch](https://developer.hashicorp.com/terraform/language/modules/sources#github) with e.g.:
```
source = "git::https://github.com/oracle-terraform-modules/terraform-oci-oke.git?ref=5.x&depth=1"
```

Otherwise, you can continue to use `node_pools` and the existing inputs with `main`/4.x versions.

**Comment by rodrigc** [comment]
@devoncrouse If I already have a cluster deployed with `5.0.0-beta.3`, but then I update to use `source = "git::https://github.com/oracle-terraform-modules/terraform-oci-oke.git?ref=5.x&depth=1"`,

if I change my TF to use `worker_pools`, will my tfstate from the existing cluster work,
or will I have to manually hack my tfstate, or use `terraform state mv` to move things around?

**Comment by devoncrouse** [comment]
>Can I easily migrate the TF state?

We'll be reviewing the migration path from 4.x with added documentation and possibly conveniences to update tfvars, however this is initially secondary to supporting the additional features and flexibility for new resources. We added some `moved` blocks ([available starting TF 1.1](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring#moved-block-syntax)) for #733, but will likely need further accommodations for a seamless upgrade.

**Comment by devoncrouse** [comment]
I don't believe the `worker_pools` input changed between `5.0.0-beta.3` and `5.x` - `node_pools` wasn't present as an input in this version (changed from `4.x` to reflect the addition of modes other than traditional managed node pools). I do recommend using the branch for evaluation of `5.x` as there have been many fixes, but advise some caution when reviewing the plan for newer revisions.

**Comment by rodrigc** [comment]
Thanks for the clarification about the roadmap for the `5.x` branch and migration from `4.x`

**Comment by rodrigc** [comment]
One other question with regard to node_pools.

I came up with this example:

```
module "oke" {
  source = "github.com/oracle-terraform-modules/terraform-oci-oke?ref=ebdab3e1ff1f569c13f802f65c1e35b8b0647b0b"

  compartment_id = var.compartment_id
  tenancy_id     = var.tenancy_id

  ssh_private_key_path = var.ssh_private_key_path
  ssh_public_key_path  = var.ssh_public_key_path

  home_region = var.home_region
  region      = var.region

  cluster_name                = var.cluster_name
  vcn_name                    = var.vcn_name
  vcn_dns_label               = var.vcn_dns_label
  kubernetes_version          = var.kubernetes_version
  worker_pools                = {
      craig_blue = {
        shape            = "VM.Standard.E4.Flex",
        ocpus            = 2,
        memory           = 8,
        size             = 1,
        boot_volume_size = 150,
      }
      craig-es-master = {
        shape            = "VM.Standard.E4.Flex",
        ocpus            = 2,
        memory           = 12,
        size             = 3,
        boot_volume_size = 150,
        node_labels = {
          "node/type" = "craig-es-master"
        }
      }
}

  providers = {
    oci.home = oci.home
  }
}
```

That correctly created a k8s cluster, and created two node pools `craig_blue` and `craig-es-master`.

On the `craig-es-master` node pool, I could see that my custom label was applied to each node: `node/type" = "craig-es-master"`

However, if I tried to add new labels, for example:

```
      craig_blue = {
        shape            = "VM.Standard.E4.Flex",
        ocpus            = 2,
        memory           = 8,
        size             = 1,
        boot_volume_size = 150,
            node_labels = {
               "node/type" = "craig-blue",
               "node/craig1" = "blue1"
           }
      }
 ```
 
 These new labels were not applied to existing nodes in the existing node pools.
 
 Is this expected behavior or a bug in the latest 5.x branch?

**Comment by devoncrouse** [comment]
This is to be expected, as they're passed to [initial_node_labels](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_node_pool#initial_node_labels) and ultimately [kubelet's --node-labels](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/):

>Labels to add when registering the node in the cluster.

After registered, modifications to node labels will need to be made with e.g. [kubectl label nodes ...](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#label)

**Comment by devoncrouse** [comment]
The TF field is updateable, though changes will only apply to new nodes created in the pool for the above reason.

**Comment by rodrigc** [comment]
That wasn't obvious to me based on reading the documentation, and also the terraform plan output.

Thanks for this clarification on node labels!

**Comment by rodrigc** [comment]
@devoncrouse I appreciate the great detail you went through to answer my questions in this issue.  You really clarified some complicated points quite nicely.  I see no reason to leave this issue open.
