### ISSUE TITLE
5.x: Updating from 5.0.0-beta.3 to latest 5.x, Error: cyclic dependency in move statements

### ISSUE THREAD

**Issue by rodrigc** [oracle-terraform-modules/terraform-oci-oke#775]
I have two oke clusters created with `5.0.0-beta.3` of this module.

I changed the TF that was used to create these clusters with:

```
 module "oke" {
-  source  = "oracle-terraform-modules/oke/oci"
-  version = "5.0.0-beta.3"
+  #source  = "oracle-terraform-modules/oke/oci"
+  #version = "5.0.0-beta.3"
+  source = "github.com/oracle-terraform-modules/terraform-oci-oke?ref=73fc6ecd60e93b7078202cae2c497f5ba028c3de"
```

### Cluster 1

```
terraform plan
```
works fine

### Cluster 2

```
terraform plan
```

gives an error:

```
╷
│ Error: Cyclic dependency in move statements
│
│ The following chained move statements form a cycle, and so there is no final location to move objects to:
│   - .terraform/modules/oke/migration.tf:48,1: module.oke[*].module.oke.oci_containerengine_node_pool.nodepools[*] → module.oke[*].module.workers[0].oci_containerengine_node_pool.workers[*]
│   - moved.tf:11,1: module.oke.module.oke.oci_containerengine_node_pool.nodepools["np2"] → module.oke.module.workers[0].oci_containerengine_node_pool.workers["np2"]
│   - moved.tf:6,1: module.oke.module.oke.oci_containerengine_node_pool.nodepools["np1"] → module.oke.module.workers[0].oci_containerengine_node_pool.workers["np1"]
│
│ A chain of move statements must end with an address that doesn't appear in any other statements, and which
│ typically also refers to an object still declared in the configuration.
```

Any idea how to fix this, @devoncrouse @hyder @Djelibeybi ?

**Comment by devoncrouse** [comment]
Hi @rodrigc - you may need to use the [terraform state mv](https://developer.hashicorp.com/terraform/cli/commands/state/mv) command manually to address this in conjunction with the reported plan, e.g. if it threatens to destroy a resource you intend to keep.

We'll be reviewing the migration path from 4.x in time, but cleanly moving between these older pre-release versions with existing clusters hasn't been a guarantee as it's been in active development - stabilized now.

If you are able to determine what we might adjust here to better handle the transition I'd be happy to add it or take a PR.

**Comment by rodrigc** [comment]
I am working with @cwiggs who has been tracking this module since 5.0.0-beta.1

@cwiggs had previously put a bunch of `moved` statements in our terraform,
to track the changes that have been happening in the 5.0.0-beta.x releases.

However all these `moved` blocks have been added to the module
here: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/migration.tf

So, I removed all the local `moved` blocks from our Terraform,
and was able to successfully `terraform apply.

**Comment by rodrigc** [comment]
Kudos to @cwiggs for tracking changes to this module, and explaining all the logic of the `moved` statements to me.

**Comment by rodrigc** [comment]
Closing this, as a workaround exists, to remove internally maintained `moved` statements.
