### ISSUE TITLE
5.x:  If Bastion is not set to be provisioned - output "ssh_to_operator" breaks.

### ISSUE THREAD

**Issue by tb137** [oracle-terraform-modules/terraform-oci-oke#782]
Hello Guys,

By setting "create_bastion = false"  parameter, it brakes the deployment with a following error:
Error: Invalid template interpolation value
on .terraform/modules/oke/module-operator.tf line 104, in output "ssh_to_operator":
104:     ? "ssh${local.ssh_key_arg} -o ProxyCommand='ssh ${local.ssh_key_arg} -W %h:%p ${var.bastion_user}@${local.bastion_public_ip}' ${var.operator_user}@${local.operator_private_ip}" : null

The issue is that output do not check if create_bastion value set to true or false. If it's set to false it should not execute SSH command.
The output  in questions is this here:
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/c3d5a1aa46795ab50b7e27566d90b5984c9e3b93/outputs.tf#L77-L80

**Comment by rodrigc** [comment]
Right now, you need `bastion` *AND* `operator.
Operator cannot work without bastion.

If you do:

```
create_bastion=false
```

You also need:

```
create_operator = false
```

**Comment by devoncrouse** [comment]
Notes for resolution: the `format()` function with `%v` verb is safer with nulls generally vs. this kind of interpolation as written, though the output wouldn't be useful with it in this case.

We should be using an alternate command when `create_bastion = false`, and omitting the value (null) when `create_operator = false`.

**Comment by hyder** [comment]
Resolved in #798
