### ISSUE TITLE
How to change node cidr for flannel?

### ISSUE THREAD

**Issue by abatilo** [oracle-terraform-modules/terraform-oci-oke#793]
According to the OCI docs:

"The default flannel CIDR block is large enough to support 65,534 pods and 512 worker nodes, and can be increased in size to support many more"
 https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengpodnetworking_topic-flannel_CNI_plugin.htm#:~:text=The%20default%20flannel%20CIDR%20block%20is%20large%20enough%20to%20support%2065%2C534%20pods%20and%20512%20worker%20nodes%2C%20and%20can%20be%20increased%20in%20size%20to%20support%20many%20more

How do I support more than 512 nodes with this module?

**Comment by hyder** [comment]
The default CIDR for the VCN is 10.0.0.0/16 and the worker subnet is 10.0.64.0/18 which gives you a maximum of 16382 IP addresses -1. If this is not enough, you can add 4 additional CIDR ranges to the `vcn_cidrs` parameter: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/terraform.tfvars.example#L90

**Comment by abatilo** [comment]
@hyder That doesn't help me. The VCN might support more IPs for the NPN CNI but I'm asking about how to change the CIDR block for flannel.

How do I change that with this module?

**Comment by hyder** [comment]
Pods CIDR is 10.244.0.0/16 by default. You can change it here if you need to https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/terraform.tfvars.example#L190 and you must ensure it doesn't overlap with other network CIDRs. See https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/docs/configuration.adoc#configure-oke-parameters

**Comment by abatilo** [comment]
Thank you @hyder, but this is not my question. I'm asking about the node CIDR for flannel. I am not trying to change the pods CIDR. I'm asking about the node CIDR.

**Comment by hyder** [comment]
Hi,
This is not supported.
