### ISSUE TITLE
5.x How can I control the bandwidth of the Oracle LoadBalancer from code

### ISSUE THREAD

**Issue by rodrigc** [oracle-terraform-modules/terraform-oci-oke#795]
I am using the terraform-oci-oke module ( version v5.0.0-beta.3 )to provision a Kubernetes cluster.

I then followed these steps to provision ingress-nginx as an Ingress controller:
https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupingresscontroller.htm

This setup worked great.

As we scaled the load on our system, we found network performance slowed down.  Our application is streaming large amounts of network data.

My colleague @rx294 analyzed the system, and found that the Oracle Load balancer that was
automatically created by OKE when the `ingress-nginx` controller was installed was by default
capped at 100MB.

This was too low for our application.  @rx294 went into the Oracle UI and
increased the Oracle Load Balancer's limit to 1000MB and that made our application run fine.

 My question is, how can we control the bandwidth limit of the the Oracle Loadbalancer in our Kubernetes application?
 
 1.  Should we do it in terraform?
 2.  Should we do it in Kubernetes yaml?
 
 We would prefer to control these types of parameters as Infrastructure as Code, and avoid changing parameters in the Oracle UI, 
 or running ad hoc commands with the oci CLI.
 
 FYI: @rx294 @cwiggs @yaanakbr

**Comment by rodrigc** [comment]
I also filed the same question and created:
[SR 3-33950168381](https://support.oracle.com/epmos/faces/SrDetail?_adf.ctrl-state=j5lgmsfo5_9&srDetailRelativeDateParam=null&queryModeName=Technical&srNumber=3-33950168381&needSrDetailRefresh=true&_afrLoop=595760703073151)

I'm not sure if you can see that.

**Comment by 12345ieee** [comment]
This has nothing to do with this module, you do it from the Kubernetes side.

See https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingloadbalancer.htm .

**Comment by rodrigc** [comment]
Thanks, that doc has pointed me in the right direction.
Since I am installing the nginx ingress controller via the helm chart,
it looks like I need to specify the Oracle specific load balancer annotations in the service section of the helm chart:

https://github.com/kubernetes/ingress-nginx/blob/a92e7b4857b3cd7fb152f1ade5f6c3db462311b2/charts/ingress-nginx/values.yaml#L422

Do you by any chance have a pointer to a doc for that?

https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingloadbalancer.htm only has examples for directly annotating the Service object

**Comment by hyder** [comment]
You can add your own extension in your code to create an ingress load balancer of your choice and use the necessary annotations you need. But we won't do it in this project.
