### ISSUE TITLE
5.x Inconsistent application of `defined_tags` between submodules

### ISSUE THREAD

**Issue by devoncrouse** [oracle-terraform-modules/terraform-oci-oke#806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* The [cluster](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/module-cluster.tf#L72-L78) sub-module only applies user-defined entries in `defined_tags` if `use_defined_tags = true`.
* The network and workers sub-modules include them regardless (desired)

### Terraform Configuration Files

```hcl
use_defined_tags = false
defined_tags = { 
  "cluster" = {
    "custom.Tag" = "value"
  }
}
```

### Expected Behavior

User-configured entries in `defined_tags` should be applied consistently to all resources regardless of `use_defined_tags`, which should only control inclusion of module tags e.g. `state_id`, `role`, etc.

### Actual Behavior

The cluster sub-module excludes all `defined_tags` (even user-configured) when `use_defined_tags = false`.

**Comment by hyder** [comment]
Resolved by #807
