### ISSUE TITLE
5.x: Invalid dot char with cluster_autoscaler key tag name when use_defined_tags

### ISSUE THREAD

**Issue by thpham** [oracle-terraform-modules/terraform-oci-oke#808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
Terraform v1.5.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.10.1
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/oracle/oci v5.9.0
```

### Affected Resource(s)

- submodule `workers`, file: [locals.tf](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/modules/workers/locals.tf#L107)

### Terraform Configuration Files

```hcl
create_iam_resources = true
create_iam_tag_namespace = true
create_iam_defined_tags  = true
tag_namespace        = "oke"
use_defined_tags     = true 

cluster_autoscaler_install           = true
cluster_autoscaler_namespace         = "kube-system"
cluster_autoscaler_helm_version      = "9.24.0"
cluster_autoscaler_helm_values       = {}
cluster_autoscaler_helm_values_files = []

worker_pools = {
  infra = {
    description = "Node pool for infra workload",
    size        = 2, allow_autoscaler = true,
  }
  default = {
    description = "Default node pool with active workers",
    size        = 1, size_max = 3, autoscale = true,
  },
}
```

### Debug Output

![oci-oke-cluster-autoscaler-defined_tags-invalid-dot-char-bug](https://github.com/oracle-terraform-modules/terraform-oci-oke/assets/224674/c1e4c813-8be7-4676-8cfd-8b1b04437ed6)

### Expected Behavior

![oke-node-pool-defined-tags](https://github.com/oracle-terraform-modules/terraform-oci-oke/assets/224674/97315c9e-0aca-409b-ae27-bb66a33ae0b0)

### Actual Behavior

see: Debug output.

### Steps to Reproduce

1. `terraform apply`

### References

OCI tag documentation: https://docs.oracle.com/en-us/iaas/Content/Tagging/Concepts/taggingoverview.htm#limits

**Comment by hyder** [comment]
+ @devoncrouse

**Comment by devoncrouse** [comment]
Thanks @robo-cap!

**Comment by thpham** [comment]
Could you re-open this issue, I think both PR #812 and #814 are not consistent with the delimiter !
