### ISSUE TITLE
5.x add link to oke docs at Terraform registry

### ISSUE THREAD

**Issue by rodrigc** [oracle-terraform-modules/terraform-oci-oke#810]
In the Hashicorp Terraform Registry page for the oke module here: https://registry.terraform.io/modules/oracle-terraform-modules/oke/oci/latest

Please add a link to the docs for the module which are here:

https://oracle-terraform-modules.github.io/terraform-oci-oke/

Things to note:
1.  Some people (like me) go to https://registry.terraform.io/ to find appropriate terraform modules
2.  At  https://registry.terraform.io/modules/oracle-terraform-modules/oke/oci/latest, the 5.x versions show up first, so new people may feel inclined to use 5.x versions, even though 5.x has not been "officially" released.

@robo-cap

**Comment by hyder** [comment]
Completed in #813
