### ISSUE TITLE
How can we add a regional subnet w/ this module, into an existing vcn?

### ISSUE THREAD

**Issue by ubersol** [oracle-terraform-modules/terraform-oci-oke#82]
Hi, I have a simple question:

Is it possible within this module to use existing resources when creating an infrastructure? The main use case is to be able to add a regional subnet into an existing vcn? 

The module works great out of the box, but I am trying to understand how granular I can get with controlling which resources to create and which resources not to create when using the module.

In .tfvars/vars files, I did not see any options to determine any existing vcn, but rather the name etc of the vcns to be created. This works great out of the box, but not when you already have existing resources and want to utilize those.

Is this possible? if not, is there any suggestion on how we can get around this ?

**Comment by hyder** [comment]
Hi,

Thanks for your feedback. It's great to hear it's working well.

If I understand your question correctly:
1. you don't want to create a new vcn but reuse an existing vcn
2. you want to add 1 more regional subnet in addition to the workers and load balancer subnets

Both are technically possible. However, you'll need to modify the code a bit e.g. in locals.tf under root and base replace the base module outputs with the necessary ids (vcn, ig route etc). You can either hardcode the ocid values or use datasources with the necessary filter to obtain them.

  oke_network_vcn = {
    ig_route_id                = module.base.ig_route_id  //replace with existing vcn ig route id
    is_service_gateway_enabled = var.create_service_gateway 
    nat_route_id               = module.base.nat_route_id //replace with existing vcn nat route id
    newbits                    = var.newbits 
    subnets                    = var.subnets
    vcn_cidr                   = var.vcn_cidr //replace with vcn cidr block
    vcn_id                     = module.base.vcn_id //replace with vcn id
  }

You'll also need to comment the vcn submodule under base/main.tf so it doesn't create another vcn.

As for adding 1 more regional subnet, you can do so by using the subnets in the okenetwork module as an example. You'll need to add the necessary key-value pairs in newbits and subnets. You can then look the values up and use the cidrsubnet function. You need to ensure that your new regional subnet range doesn't overlap with the worker, load balancer subnets.

**Comment by ubersol** [comment]
Ok, I'll try these suggestions....in the mean time one follow up question....

In the case of when using the existing vcn, if I do terraform destroy will that also remove/destroy the existing vcn ? I am basically trying to understand the granularity of the controls I have.

**Comment by hyder** [comment]
No, it won't destroy the vcn because you won't be creating it with Terraform. Terraform will only destroy the resources it creates

**Comment by ubersol** [comment]
ok Thank you!
