### ISSUE TITLE
[v5.0.0-RC4] BUG  create_drg=true has no effect

### ISSUE THREAD

**Issue by lodotek** [oracle-terraform-modules/terraform-oci-oke#822]
As mentioned here: https://github.com/oracle-terraform-modules/terraform-oci-oke/commit/5a33900bcc673483ce892d2c62b7f3e8a6660da3#r126242411

It appears that for some reason the DRG module was commented out, as a result my DRG and its attachments want to be deleted by TF when I run a plan 

Please advise.

**Comment by hyder** [comment]
Hi,
We were thinking of removing the DRG module. Can you please tell us your use case?

**Comment by lodotek** [comment]
Why would you guys remove the DRG Module? I'm using it to support remote VCN peering connections as I'm replicating MySQL DBs across VCNs in differing regions.

**Comment by devoncrouse** [comment]
@lodotek The DRG resource can be created on its own from the OCI provider, possibly using the outputs from this module as needed (e.g. if the VCN was created here). Embedding in this module adds complexity to it and limits configuration options.

See [core_drg](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_drg) and [core_drg_attachment](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_drg_attachment) for information on creating the resources directly, and [terraform/cli/commands/state/mv](https://developer.hashicorp.com/terraform/cli/commands/state/mv) to update an existing Terraform state to reflect the change.

**Comment by kral2** [comment]
Hello,
The plan since long time was to eventually spin off DRG into its own module at some point.

I am not current enough anymore with the vcn module to know if that moment is now, but it is a logical evolution as drg gets more and more features to make it separate.

**Comment by lodotek** [comment]
Is this issue related: https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/833 ?

**Comment by hyder** [comment]
resolved in #842
