### ISSUE TITLE
[5.x] Support node cycling in terraform-oci-oke module

### ISSUE THREAD

**Issue by rodrigc** [oracle-terraform-modules/terraform-oci-oke#823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support node cycling in the terraform-oci-oke module

### New or Affected Resource(s)

[oci_containerengine_node_pool](https://registry.terraform.io/providers/oracle/oci/5.0.0/docs/resources/containerengine_node_pool)

### Potential Terraform Configuration

In the [oracle/oci](https://registry.terraform.io/providers/oracle/oci/) module,
the [oci_containerengine_node_pool](https://registry.terraform.io/providers/oracle/oci/5.0.0/docs/resources/containerengine_node_pool) resource has a flag:
`is_node_cycling_enabled`.

If we (QuickNode) could pass this value down from the `terraform-oci-oke` module to the `oracle/oci` module,
that might get QuickNode to where we need to go.

If this approach will not work, then I will use this ticket to request node cycling support
in the terraform-oci-oke module by some mechanism

### References

* [Slack thread discussion with Oracle](https://quicknode.slack.com/archives/C04CSA5NPNX/p1693599012688169?thread_ts=1693598977.626919&cid=C04CSA5NPNX)

**Comment by hyder** [comment]
Resolved in #830
