### ISSUE TITLE
Cluster Name is Ignored when creating kubeconfig

### ISSUE THREAD

**Issue by liamhelmer** [oracle-terraform-modules/terraform-oci-oke#826]
Currently using Provider 5.0.0-RC4
when a cluster is created with a specific name, that name is ignored in the kube_config that's output. In this instance, I set cluster_name as cicdcluster. This name was used just fine in the creation of the cluster. However, the generated kubeconfig uses a random name instead of the cluster name. I would expect that cluster_name would be used when generating the kubeconfig instead.

Current output of cluster_kubeconfig:

`{
  "apiVersion" = "v1"
  "clusters" = [
    {
      "cluster" = {
        "certificate-authority-data" = "REDACTED"
        "server" = "https://REDACTED:6443"
      }
      "name" = "cluster-cnitcejzuna"
    },
  ]
  "contexts" = [
    {
      "context" = {
        "cluster" = "cluster-cnitcejzuna"
        "user" = "user-cnitcejzuna"
      }
      "name" = "context-cnitcejzuna"
    },
  ]
  "current-context" = "context-cnitcejzuna"
  "kind" = ""
  "users" = [
    {
      "name" = "user-cnitcejzuna"
      "user" = {
        "exec" = {
          "apiVersion" = "client.authentication.k8s.io/v1beta1"
          "args" = [
            "ce",
            "cluster",
            "generate-token",
            "--cluster-id",
            "ocid1.cluster.oc1.ca-toronto-1.REDACTED",
            "--region",
            "ca-toronto-1",
          ]
          "command" = "oci"
          "env" = []
        }
      }
    },
  ]
}`

Current module configuration (let me know if any of the variables are relevant to you):

`module "cicd-cluster" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "5.0.0-RC4"
  compartment_id = module.cis-landingzone-pre-config.lz_top_compartments.cicd.id
  cluster_name = "cicdcluster"
  #tenancy_id = var.tenancy_ocid
  create_bastion = false
  assign_dns = true
  create_vcn = true
  cluster_dns = null
  cluster_kms_key_id = null
  cni_type = "flannel"
  cluster_type = "basic"
  kubernetes_version = "v1.26.2"
  use_signed_images = false
  bastion_allowed_cidrs = local.control_plane_allowed_cidrs
  create_cluster = true
  create_operator = false
  output_detail = true
  pods_cidr = "172.31.0.0/16"
  services_cidr = "172.29.0.0/16"
  vcn_cidrs = [ "172.30.0.0/16" ]
  control_plane_is_public = true
  control_plane_allowed_cidrs = local.control_plane_allowed_cidrs
  ssh_public_key = tls_private_key.devops_root_ssh.public_key_openssh
  ssh_private_key = tls_private_key.devops_root_ssh.private_key_openssh
  providers = { oci.home = oci.home, oci = oci }
  }`

**Comment by hyder** [comment]
Hello, sorry for the belated reply. 

You can change the context name by running the command:

```kubectx <cluster_name>```

Would you like this to be automated?

**Comment by hyder** [comment]
Resolved in #840
