### ISSUE TITLE
Assigned enable_instance_principal as false, still trying to create dynamic group.

### ISSUE THREAD

**Issue by narendradotg** [oracle-terraform-modules/terraform-oci-oke#85]
Team,

I have assigned enable_instance_principal as false and use_encryption as false in terraform.tfvars, still it is trying to create dynamic policy

few lines from terraform.tfvars
-----------------------------
create_bastion = true
bastion_access = "ANYWHERE"
enable_instance_principal = false
use_encryption = false

rror: Invalid index

  on modules/policies/locals.tf line 10, in locals:
  10:   policy_statement = "Allow dynamic-group ${oci_identity_dynamic_group.oke-kms-cluster[0].name} to use keys in compartment ${var.oci_identity.compartment_name} where target.key.id = '${var.oke_kms.key_id}'"
    |----------------
    | oci_identity_dynamic_group.oke-kms-cluster is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on modules/base/bastion/outputs.tf line 9, in output "bastion_instance_principal_group_name":
   9:   value = oci_identity_dynamic_group.bastion_instance_principal[0].name
    |----------------
    | oci_identity_dynamic_group.bastion_instance_principal is empty tuple

The given key does not identify an element in this collection value.

**Comment by hyder** [comment]
Hi @narendradotg, thanks for reporting. We'll investigate.

**Comment by hyder** [comment]
Hi @narendradotg, I was not able to replicate the issue but someone else was. I've added a few more checks in this branch: https://github.com/hyder/terraform-oci-oke/tree/issue_85 . Can you please try?

git clone https://github.com/hyder/terraform-oci-oke.git
git checkout issue_85

Copy your existing terraform variable file and run a plan.

Thanks

**Comment by livespotty** [comment]
Hi @hyder , I tested and verified. Thanks.

**Comment by hyder** [comment]
fixed in #92

**Comment by hyder** [comment]
thanks @livespotty
