### ISSUE TITLE
Use compartment id instead of name to write policy statement

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-terraform-modules/terraform-oci-oke#86]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In the following policy statement in `modules/policies/locals.tf`:

`policy_statement = "Allow dynamic-group ${oci_identity_dynamic_group.oke-kms-cluster[0].name} to use keys in compartment ${var.oci_identity.compartment_name} where target.key.id = '${var.oke_kms.key_id}'"`

... consider using the compartment id instead of the name. That way, we can remove the need for users to enter the compartment name in `tfvars`.  Similar to the implementation in https://github.com/oracle-terraform-modules/terraform-oci-base/blob/master/modules/bastion/iam.tf

**Comment by kumar-dhanagopal** [comment]
https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/93

**Comment by hyder** [comment]
Fixed in #107
