### ISSUE TITLE
Cloud-Init Failure

### ISSUE THREAD

**Issue by KingMichaelPark** [oracle-terraform-modules/terraform-oci-oke#868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

1.5.7
oci oke module 5.0.2

### Affected Resource(s)

`module.oke.module.bastion[0].null_resource.await_cloudinit`

latest oci

### Debug Output

```
│ Error: remote-exec provisioner error
│
│   with module.oke.module.bastion[0].null_resource.await_cloudinit,
│   on .terraform/modules/oke/modules/bastion/cloudinit.tf line 44, in resource "null_resource" "await_cloudinit":
│   44:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1057178348.sh": Process exited with status
│ 1
╵
```

### Expected Behavior

The cloud init step of the provider should run.

### Actual Behavior

This is the output from the /tmp/terraform.sh command that cloud-init runs which is simply
the `cloud-init status --wait -l` command.

```bash
Welcome to Oracle Autonomous Linux
Effective kernel version is 5.15.0-101.103.2.1.el8uek.x86_64
[opc@b-rxwscc ~]$ sudo dnf -y upgrade
This system is receiving updates from OSMS server.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
[opc@b-rxwscc ~]$ cloud-init status --wait -l

status: error
time: Mon, 13 Nov 2023 19:25:23 +0000
detail:
('package-update-upgrade-install', ProcessExecutionError("Unexpected error while running command.\nCommand: ['dnf', '-y', 'upgrade']\nExit code: 1\nReason: -\nStdout: -\nStderr: -",))
[opc@b-rxwscc ~]$
```

### Steps to Reproduce

1. `terraform apply`
2. Wait for the `await_cloudinit` null resource to run

### Important Factoids

uk-london-1
I did have bastion_upgrade and operator_upgrade set to `true` instead of `false`

**Comment by KingMichaelPark** [comment]
Okay so doing a force-recreate of the bastion and operator worked when I set the do_upgrade flags for the bastion and operator to false. It's because Autonomous Linux uses a different mechanism for upgrades to dnf so the dnf command needs to be skipped. I would assume this might work with upgrades enabled if you were to use Oracle Linux instead of Autonomous. Nonetheless, there should be a cross-check in my opinion.

**Comment by robo-cap** [comment]
I was not able to reproduce the problem described:

**Comment by KingMichaelPark** [comment]
- Autonomous Linux
- bastion_upgrade=true
- operator_upgrade=true

**Comment by robo-cap** [comment]
```
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Tue Nov 14 08:15:17 2023 from 86.127.153.72
Welcome to Oracle Autonomous Linux
Effective kernel version is 5.15.0-101.103.2.1.el8uek.x86_64
[opc@b-cxcccv ~]$ cloud-init status --wait -l

status: done
time: Tue, 14 Nov 2023 08:07:42 +0000
detail:
DataSourceOracle
```

The operator is a different resource, deployed after the bastion host. The `operator_upgrade` variable has no impact.
