### ISSUE TITLE
Wrong `control_plane_is_public` behavior for OKE cluster

### ISSUE THREAD

**Issue by Noksa** [oracle-terraform-modules/terraform-oci-oke#869]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

```
resource "oci_containerengine_cluster" "k8s_cluster"
resource "oci_core_subnet" "oke"
resource "oci_containerengine_node_pool" "workers"
```

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior

I think `control_place_is_public` should work the same way as it works via `web` console.
We should be able to enable/disable public endpoint at any time changing `control_place_is_public` if we create it with `true` (cp subnet is public).

For instance, if we create `OKE` cluster using `web` console in public subnet, we are able to enable/disable public api endpoint at any time:
<img width="1298" alt="image" src="https://github.com/oracle-terraform-modules/terraform-oci-oke/assets/36312857/98942764-6c1c-48dd-8e0d-dc45d563c4ce">

### Actual Behavior

Currently, it is impossible to change `control_place_is_public` from `true` to `false` without recreating the whole OKE cluster.

Using terraform, if we created an OKE cluster with `control_plane_is_public` set to `true` and we change it to `false`, terraform wants to recreate the whole OKE cluster from scratch. I guess the root cause might be here: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/667bb239fcdc57da59fa74e64c448edb4529b34c/modules/network/subnets.tf#L131

When it is `false`, public subnet wants to be private instead because of `prohibit_public_ip_on_vnic`

### Steps to Reproduce

Use 

```
module "oke" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "5.0.0"
}
```

1. Just create a simple cluster using terraform with `control_plane_is_public` set to `true`
2. Change `control_plane_is_public` to false
3. Run `terraform plan` and check that everything should be replaced

```
 # module.oke.module.cluster[0].oci_containerengine_cluster.k8s_cluster must be replaced
+/- resource "oci_containerengine_cluster" "k8s_cluster" {
      ~ available_kubernetes_upgrades = [] -> (known after apply)
    ...
      ~ endpoint_config {
          ~ is_public_ip_enabled = true -> false
          ~ subnet_id            = "ocid1.subnet.oc1.SOME_ID" # forces replacement -> (known after apply) # forces replacement
            # (1 unchanged attribute hidden)
        }
    ...
```

```
  # module.oke.module.network.oci_core_subnet.oke["cp"] must be replaced
+/- resource "oci_core_subnet" "oke" {
      + availability_domain        = (known after apply)
      ...
      ~ prohibit_public_ip_on_vnic = false -> true # forces replacement
```

```
  # module.oke.module.workers[0].oci_containerengine_node_pool.workers["general"] must be replaced
-/+ resource "oci_containerengine_node_pool" "workers" {
      ~ cluster_id          = "ocid1.cluster.oc1.SOME_ID" # forces replacement -> (known after apply) # forces replacement
```

**Comment by syedthameem85** [comment]
@Noksa  / @hyder / @devoncrouse
With public subnets, we have option to either assign public IP or defer it for assignment at a later point of time. This is the feature that is being used to assign or unassign the public IP to Control plane API endpoint in OCI console. So if the cluster has been created with public subnet with/without actually assigning the public IP at the time off creation, there should be an option to toggle the public IP after cluster is provisioned.

The variable `control_plane_is_public` is being used in code to decide the subnet type (public or private). If we toggle this variable, the subnet recreation will kick off which will recreate the cluster and nodepools.

For solution to toggle the public ip , we need to introduce a new boolean variable (`assign_public_ip_to_control_plane`) to toggle public ip on control plan API endpoint.  

With `control_plane_is_public` set to true, `assign_public_ip_to_control_plane` can be set to either `true` or `false`. 
1. When `assign_public_ip_to_control_plane` is set to `true`, the public IP will be assigned to Control plane API endpoint. 
2. When `assign_public_ip_to_control_plane` set to `false`, although the subnet is public, the public IP will not be assigned to the API endpoint.

With `control_plane_is_public` set to false, public ip will not be allocated to API endpoint irrespective of value set for `assign_public_ip_to_control_plane`
