### ISSUE TITLE
TLS handshake timeout for API call to OKE service

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-terraform-modules/terraform-oci-oke#87]
I'm running into a strange issue, which I'm discussing with @hyder.  It appears to be an issue with the service or tenancy, not the TF code per se.  I'm posting here just in case any of the other contributors/users have seen this issue -- either when using this repo or any other.

I cloned this repo, set the variables, and tried applying the configuration....

The bastion & network resources were created alright. 

But the k8s cluster resources weren't created. Here's the error:

```
Error: Post https://containerengine.us-phoenix-1.oraclecloud.com/20180222/clusters: net/http: TLS handshake timeout
  on modules/oke/cluster.tf line 4, in resource "oci_containerengine_cluster" "k8s_cluster":
   4: resource "oci_containerengine_cluster" "k8s_cluster" {
```

Ali and I suspected a proxy issue initially . But then why would the API request to the OKE service alone time out when the calls to the other services work fine?  I get the same error when I change the region to Ashburn.

**Comment by hyder** [comment]
We'll keep this open for a while in case others run into it.

**Comment by kumar-dhanagopal** [comment]
I don't see this issue anymore and am able to apply the config. I'm not sure what caused the issue. But if no one else has experienced this error, then we can safely close the issue.
