### ISSUE TITLE
boot_volume_size takes no effect in 4.x

### ISSUE THREAD

**Issue by icy** [oracle-terraform-modules/terraform-oci-oke#878]
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/18a09cdd6c100c1437f1fecc7fcfabc5da51aeec/modules/oke/nodepools.tf#L142

because of `lifecycle` setting, changing `boot_volume_size` doesn't take any effect.

on 5.x this is commented out: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/modules/workers/nodepools.tf#L124

**Comment by hyder** [comment]
Hi,

Which specific version are you using? Can you please share either the release version or the commit id?

**Comment by hyder** [comment]
Can you please try the following test and let me know the result (without commenting the line above as you did to make it work):

Create a new node pool with 1 worker starting with workers' boot volume starting at 100GB.
What is the boot volume size on its worker node after creation?

Change the node pool configuration to 150 GB and run terraform apply again.
What is the boot volume size on its worker node after creation?

Delete the worker node and wait OKE to reconcile and recreate the new worker node. What is the new worker node's boot volume size?

**Comment by icy** [comment]
Hi @hyder ,

Thanks for your question. I think I've confused you, so your  question would help to clarify the situation. I write notes from our past tests (not new test), because I can't really allocate the cluster for testing now (but maybe later). 

Please let me know if that helps and/or you need more information: 

> Can you please try the following test and let me know the result (without commenting the line above as you did to make it work):
> 
> Create a new node pool with 1 worker starting with workers' boot volume starting at 100GB. What is the boot volume size on its worker node after creation?

When creating new pool, the configuration matched with the newly created object. It's 50GB in our pool setting. I think this is also the  default value.

> Change the node pool configuration to 150 GB and run terraform apply again. What is the boot volume size on its worker node after creation?

After the pool was created and if I changed `boot_volume_size` to 200GB and asked Terraform to apply my changes, the new configuration didn't have any effect. When the old node was torn down , new node was created with the old configuration 50GB in their boot volumes.

> 
> Delete the worker node and wait OKE to reconcile and recreate the new worker node. What is the new worker node's boot volume size?

For now I don't have answer to this question. I may test and give you update later.

Thanks

NB: as a work-around, our team keeps a local patch of the file `nodepools.tf` (In this patch file I simply comment out the line as specified above) in the `.terraform/` folder so that the team can update the boot_volume_size when they need.

**Comment by hyder** [comment]
> Hi @hyder ,
> 
> Thanks for your question. I think I've confused you, so your question would help to clarify the situation. I write notes from our past tests (not new test), because I can't really allocate the cluster for testing now (but maybe later).
> 
> Please let me know if that helps and/or you need more information:
> 
> > Can you please try the following test and let me know the result (without commenting the line above as you did to make it work):
> > Create a new node pool with 1 worker starting with workers' boot volume starting at 100GB. What is the boot volume size on its worker node after creation?
> 
> When creating new pool, the configuration matched with the newly created object. It's 50GB in our pool setting. I think this is also the default value.
> 
50GB would get allocated anyway if you don't specify any. It's the default. I want to understand if you set any amount > 50GB, this value takes effect from creation. 

> > Change the node pool configuration to 150 GB and run terraform apply again. What is the boot volume size on its worker node after creation?
> 
> After the pool was created and if I changed `boot_volume_size` to 200GB and asked Terraform to apply my changes, the new configuration didn't have any effect. When the old node was torn down , new node was created with the old configuration 50GB in their boot volumes.
> 
> > Delete the worker node and wait OKE to reconcile and recreate the new worker node. What is the new worker node's boot volume size?
> 
> For now I don't have answer to this question. I may test and give you update later.
> 
IIRC, the way we did this was for the changes to take effect in new worker nodes of the same pools. That's what I would like to test.

> Thanks
> 
> NB: as a work-around, our team keeps a local patch of the file `nodepools.tf` (In this patch file I simply comment out the line as specified above) in the `.terraform/` folder so that the team can update the boot_volume_size when they need.

**Comment by icy** [comment]
Yes I see. Let me align with the team for some testing and I will keep you posted. Cheers.

**Comment by hyder** [comment]
Hi,

I'm going to close this. Please reopen if this is still an issue.

**Comment by hyder** [comment]
Ok thanks for letting us know.
