### ISSUE TITLE
OKE deployment should not manadate NAT Gateway

### ISSUE THREAD

**Issue by johncmhorton** [oracle-terraform-modules/terraform-oci-oke#887]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently this module requires private subnets to have a NAT Gateway to deploy a cluster successfully. The documentation says this is required specifically if resources in the private subnet will need internet access, but not in all cases. 
ref: https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengnetworkconfig.htm
(my bold)
> If you intend to use private subnets (for worker nodes, the Kubernetes API endpoint, or pods when using the OCI VCN-Native Pod Networking CNI plugin) **and the subnets require access to the internet**, the VCN must have a NAT gateway.

**Comment by hyder** [comment]
Not an issue. Closing
