### ISSUE TITLE
Default values for cluster autoscaler helm chart cannot be overridden correctly

### ISSUE THREAD

**Issue by VladislavGeneDx** [oracle-terraform-modules/terraform-oci-oke#922]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
$ tf version
Terraform v1.7.5
on darwin_amd64
```
Module version: "5.1.2"

### Affected Resource(s)

module.oke.module.extensions[0].data.helm_template.cluster_autoscaler[0]

### Terraform Configuration Files

```hcl
module "oke" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "5.1.2"

  providers = { oci.home = oci }

  ...
  # Cluster autoscaler environment variables
  cluster_autoscaler_install           = true
  cluster_autoscaler_namespace         = "kube-system"
  cluster_autoscaler_helm_version      = "9.37.0" 
  cluster_autoscaler_helm_values       = {
    "cloudProvider" = "oci",
    "image.tag"     = "1.29.0-10",
  }
  ...
}

```

### Expected Behavior

We expected that the default values in the generated helm chart would be overridden by provided variables. 

### Actual Behavior

The provided values were ignored. 

### Steps to Reproduce

Provide to the oke module custom values like in the example below via cluster_autoscaler_helm_values variable.  

### Important Factoids

If you add variables to[ autoscaler helm](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/modules/extensions/autoscaler.tf#L75) chart it will override the default values only if the value of a variable is sorted lower in alphanumeric order then default one.
It happens because the order of sets in helm_template doesn't affect the order of applied variables. It creates toset(), which sorts all values in alphanumeric order and uses the latest one.

```
terraform console
> toset([{ "name" = "cloudProvider", "type" = "", "value" = "oci" }, { "name" = "cloudProvider", "type" = "", "value" = "oci-oke" }])
toset([
  {
    "name" = "cloudProvider"
    "type" = ""
    "value" = "oci"
  },
  {
    "name" = "cloudProvider"
    "type" = ""
    "value" = "oci-oke"
  },
])
> toset([{ "name" = "cloudProvider", "type" = "", "value" = "oci-oke" }, { "name" = "cloudProvider", "type" = "", "value" = "oci" }])
toset([
  {
    "name" = "cloudProvider"
    "type" = ""
    "value" = "oci"
  },
  {
    "name" = "cloudProvider"
    "type" = ""
    "value" = "oci-oke"
  },
])
> toset([{ "name" = "cloudProvider", "type" = "", "value" = "a" }, { "name" = "cloudProvider", "type" = "", "value" = "b" }])
toset([
  {
    "name" = "cloudProvider"
    "type" = ""
    "value" = "a"
  },
  {
    "name" = "cloudProvider"
    "type" = ""
    "value" = "b"
  },
])
> toset([{ "name" = "cloudProvider", "type" = "", "value" = "b" }, { "name" = "cloudProvider", "type" = "", "value" = "a" }])
toset([
  {
    "name" = "cloudProvider"
    "type" = ""
    "value" = "a"
  },
  {
    "name" = "cloudProvider"
    "type" = ""
    "value" = "b"
  },
```

It's possible to fix by merging values before set: replace [these lines](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/modules/extensions/autoscaler.tf#L65-L81) with something like:
```
  dynamic "set" {
    for_each = merge(local.cluster_autoscaler_defaults, var.cluster_autoscaler_helm_values)
    iterator = helm_value
    content {
      name  = helm_value.key
      value = helm_value.value
    }
  }
```

**Comment by hyder** [comment]
Resolved in #926
