### ISSUE TITLE
Doc:  Displaying bastion ssh page returns 404 

### ISSUE THREAD

**Issue by j2joi** [oracle-terraform-modules/terraform-oci-oke#929]
Current documentation does not display bastion ssh entry - https://oracle-terraform-modules.github.io/terraform-oci-oke/guide/guide/bastion_ssh.html - correctly. 

error message displayed: [Document not found (404)](https://oracle-terraform-modules.github.io/#document-not-found-404)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by hyder** [comment]
Your link is wrong, you have "guide" twice in your link. It should be https://oracle-terraform-modules.github.io/terraform-oci-oke/guide/bastion_ssh.html and it's working fine.
