### ISSUE TITLE
unable to provision oke with cilium install

### ISSUE THREAD

**Issue by ddevadat** [oracle-terraform-modules/terraform-oci-oke#958]
i tried to use oke module with cilium install 

  cilium_install                     = true
  cilium_helm_version                = "1.16.3"
  
  Is there an example values for setting cilium_helm_values?

I tried without passing any values, but it fails with this error
```
│ Error: execution error at (cilium/templates/validate.yaml:25:5): containerRuntime.integration was deprecated in v1.14 and has been removed in v1.16. For details please refer to https://docs.cilium.io/en/v1.16/operations/upgrade/#helm-options
│
│   with module.k8s_infra.module.extensions[0].data.helm_template.cilium[0],
│   on .terraform/modules/k8s_infra/modules/extensions/cilium.tf line 134, in data "helm_template" "cilium":
│  134: data "helm_template" "cilium" {
```

**Comment by robo-cap** [comment]
The error you are seeing indicates you are trying to set `containerRuntime.integration` value on cilium 1.16 helm chart. This is not supported.

The support for cilium 1.16 was added with the OKE TF module 5.2 release.


Regarding an example for the values, please take a look here: https://oracle-terraform-modules.github.io/terraform-oci-oke/guide/extensions_networking.html#cilium-cni

**Comment by ddevadat** [comment]
thanks this is working now. i was using 5.18 version
