### ISSUE TITLE
Provisiong burstable worker nodes when added in instance or instance-pool mode

### ISSUE THREAD

**Issue by ddevadat** [oracle-terraform-modules/terraform-oci-oke#968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Potential Terraform Configuration

When worker nodes are added as instance pool or instance , we need an ability to define burstability. Currently its not possible to add a worker in instance or instance-pool mode , with this flag. I have given a sample below for adding baseline_ocpu_utilization in the shape_config

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 

      dynamic "shape_config" {
        for_each = length(regexall("Flex", each.value.shape)) > 0 ? [1] : []
        content {
          baseline_ocpu_utilization = lookup(each.value, "burst", "BASELINE_1_1")
          ocpus = each.value.ocpus
          memory_in_gbs = ( # If > 64GB memory/core, correct input to exactly 64GB memory/core
            (each.value.memory / each.value.ocpus) > 64 ? each.value.ocpus * 64 : each.value.memory
          )
        }
      }
```

**Comment by hyder** [comment]
resolved in #970
