### ISSUE TITLE
OKE service CIDR and Pod CIDR selection

### ISSUE THREAD

**Issue by Rahul06151** [oracle-terraform-modules/terraform-oci-oke#97]
Can we use same pods_cidr(10.244.0.0/16) and services_cidr(10.96.0.0/16) while creating OKE cluster for multiple environments keeping same VCN CIDR(10.0.0.0/16). Will their be any conflict in any of the services.

**Comment by hyder** [comment]
Yes you can. As long as 1) the pods_cidr and services_cidr do not overlap with the vcn_cidr block and worker+load balancer CIDR blocks respectively 2) you do not plan on connecting the multiple environment through peering

**Comment by hyder** [comment]
The cidr blocks requirements are outlined here: https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengcidrblocks.htm
